# Deutscher Wetterdienst

## Overview

### Available weather data

[General information](https://www.dwd.de/DE/leistungen/cdc/cdc_ueberblick-klimadaten.html?nn=16102)

[Technical information](https://www.dwd.de/DE/leistungen/opendata/hilfe.html)

- available measurement frequency (dependent on parameter and location)
    - 1 min
    - 10 min
    - **hourly**
    - **daily**
    - monthly
    - quaterly

> highest relevance: daily and hourly

- available parameters
    - **solar irradiation**
    - **sunshine hours per day**
    - air pressure
    - temperature
    - **cloudiness**
    - humidity
    - soil condition
    - **visibility**
    - **wind**
    - **precipitation incl. snow**
    - **weather phenomena** (e.g. hail, storm, ...)

> highest relevance: solar features, cloudiness, visibility, wind, precipitation, phenomena 

- also available: some aggregated data (e.g. monthly by federal state), derived parameters, measurements by radiosonde

### Solar Data

- [description](https://opendata.dwd.de/climate_environment/CDC/observations_germany/climate/daily/solar/DESCRIPTION_obsgermany_climate_daily_solar_en.pdf)
    - global radiation, diffuse radiation, sunshine duration
    - hours, J/cm2
    - variables:
        - longwave downward radiation
        - daily sum of diffuse solar radiation
        - daily sum of solar incoming radiation
        - daily sum of sunshine duration
- daily solar [data](https://opendata.dwd.de/climate_environment/CDC/observations_germany/climate/daily/solar/ST_Tageswerte_Beschreibung_Stationen.txt)

```csv
Stations_id von_datum bis_datum Stationshoehe geoBreite geoLaenge Stationsname Bundesland
----------- --------- --------- ------------- --------- --------- ----------------------------------------- ----------
00183 19810101 20230630     42     54.6791   13.4344 Arkona                                 Mecklenburg-Vorpommern
00656 19570101 20000731            607     51.7234   10.6021 Braunlage                                Niedersachsen
00662 19580101 20230630             81     52.2915   10.4464 Braunschweig                             Niedersachsen
00691 20090101 20230630              4     53.0451    8.7981 Bremen                                   Bremen
00853 19810101 20230630            416     50.7913   12.8720 Chemnitz                                 Sachsen
00867 20210101 20230630            344     50.3066   10.9679 Lautertal-Oberlauter                     Bayern
01048 19960901 20230630            228     51.1278   13.7543 Dresden-Klotzsche                        Sachsen
01358 19580101 20230630           1213     50.4283   12.9536 Fichtelberg                              Sachsen
01443 19730101 20150131            237     48.0232    7.8343 Freiburg                                 Baden-Württemberg
01580 19760101 20131231            111     49.9859    7.9548 Geisenheim                               Hessen
01594 19740101 19901231             44     51.5068    7.0945 Gelsenkirchen                            Nordrhein-Westfalen
01684 20010101 20230630            239     51.1621   14.9506 Görlitz                                  Sachsen
01957 19810101 20150131             93     51.5138   11.9499 Halle-Kröllwitz                          Sachsen-Anhalt
01975 20050101 20230630             11     53.6332    9.9881 Hamburg-Fuhlsbüttel                      Hamburg
02290 19530101 20230630            977     47.8009   11.0108 Hohenpeißenberg                          Bayern
02532 19790101 20021231            231     51.2963    9.4424 Kassel                                   Hessen
02712 19770101 20230630            428     47.6952    9.1307 Konstanz                                 Baden-Württemberg
02925 20210101 20230630            356     51.3932   10.3123 Leinefelde                               Thüringen
02928 20060101 20191231            138     51.3151   12.4462 Leipzig-Holzhausen                       Sachsen
02932 20190101 20230630            131     51.4347   12.2396 Leipzig/Halle                            Sachsen
03015 19810101 20230630             98     52.2085   14.1180 Lindenberg                               Brandenburg
03028 19820101 20111231            157     51.7854    8.8388 Lippspringe, Bad                         Nordrhein-Westfalen
03032 19720101 20150131             25     55.0110    8.4125 List auf Sylt                            Schleswig-Holstein
03098 20060101 20130731            387     51.2452    7.6425 Lüdenscheid                              Nordrhein-Westfalen
03478 19910101 20031231             81     53.5468   13.1914 Neubrandenburg                           Mecklenburg-Vorpommern
03631 19640101 20230630             12     53.7123    7.1519 Norderney                                Niedersachsen
03668 20090101 20230630            314     49.5030   11.0549 Nürnberg                                 Bayern
03815 19770101 20011231             95     52.2553    8.0534 Osnabrück                                Niedersachsen
03987 19451231 20230630             81     52.3812   13.0622 Potsdam                                  Brandenburg
04271 19980101 20230630              5     54.1803   12.0808 Rostock-Warnemünde                       Mecklenburg-Vorpommern
04336 19810101 20230630            319     49.2128    7.1077 Saarbrücken-Ensheim                      Saarland
04393 20080101 20230630              5     54.3279    8.6031 Sankt Peter-Ording                       Schleswig-Holstein
04466 19800101 20230630             43     54.5275    9.5487 Schleswig                                Schleswig-Holstein
04642 19910101 20230630             21     52.8911   11.7297 Seehausen                                Sachsen-Anhalt
04928 19790101 20230630            314     48.8281    9.2000 Stuttgart (Schnarrenberg)                Baden-Württemberg
05100 19580101 20230630            261     49.7479    6.6583 Trier-Petrisberg                         Rheinland-Pfalz
05142 20220101 20230630              1     53.7445   14.0698 Ueckermünde                              Mecklenburg-Vorpommern
05282 19500101 19960831            246     51.1197   13.6744 Wahnsdorf bei Dresden                    Sachsen
05404 19610101 20230630            477     48.4024   11.6946 Weihenstephan-Dürnast                    Bayern
05419 19490101 20070430            264     50.9751   11.3076 Weimar                                   Thüringen
05440 19810101 20141031            439     49.0115   10.9308 Weißenburg-Emetzheim                     Bayern
05705 19570101 20230630            268     49.7704    9.9576 Würzburg                                 Bayern
05779 19810101 20230630            877     50.7313   13.7516 Zinnwald-Georgenfeld                     Sachsen
05792 20130101 20230630           2956     47.4210   10.9848 Zugspitze                                Bayern
05856 19970102 20230630            476     48.5451   13.3532 Fürstenzell                              Bayern
05906 19790101 20230630             98     49.5063    8.5584 Mannheim                                 Baden-Württemberg
06197 20220101 20230630            258     51.8664    9.2710 Lügde-Paenbruch                          Nordrhein-Westfalen
07370 20210101 20230630            499     49.3910   12.6838 Waldmünchen                              Bayern
```

- further solar data [Berlin](https://opendata.dwd.de/climate_environment/CDC/observations_germany/climate_urban/hourly/sun/recent/) 2015 - current
- further solar data [Hamburg, Dresden, Hannover](https://opendata.dwd.de/climate_environment/CDC/observations_germany/climate_urban_prov/hourly/sun/recent/) -  2017/18 - 2017/21/current

### About the Metadata

Typical files in solar data zip folder:
- Metadaten_Stationsname_Betreibername_00183.html  
- Metadaten_Stationsname_Betreibername_00183.txt  
- Metadaten_Parameter_st_stunde_00183.html  
- Metadaten_Parameter_st_stunde_00183.txt  
- Metadaten_Geraete_Atmosphaere_Lw_J_00183.html  
- Metadaten_Geraete_Atmosphaere_Lw_J_00183.txt  
- Metadaten_Geraete_Diffus_Himmel_Kw_J_00183.html  
- Metadaten_Geraete_Diffus_Himmel_Kw_J_00183.txt  
- Metadaten_Geraete_Global_Kw_J_00183.html  
- Metadaten_Geraete_Global_Kw_J_00183.txt  
- Metadaten_Geraete_Sonnenscheindauer_00183.html  
- Metadaten_Geraete_Sonnenscheindauer_00183.txt  
- Metadaten_Geographie_00183.txt  
- **produkt_st_stunde_19810101_20230630_00183.txt**

Note: some locations of the measurement may have changed slightly (e.g. 00183 Metadaten_Geographie_00183.txt)

```csv Metadaten_Geographie_00183.txt  
Stations_id;Stationshoehe;Geogr.Breite;Geogr.Laenge;von_datum;bis_datum;Stationsname
183;   42.00; 54.6804; 13.4327;18780601;19460831;Arkona
183;   42.00; 54.6791; 13.4345;19460901;20060810;Arkona
183;   42.00; 54.6791; 13.4344;20060811;20110903;Arkona
183;   42.00; 54.6791; 13.4344;20110904;        ;Arkona
```


## Preparation

In [1]:
# # clean up before starting the download
# !rm -rf ./data/weather/*
# !rm -rf ./data/weather-daily/*
# !rm -rf ./data/weather-hourly/*

In [2]:
# for web download
from bs4 import BeautifulSoup
import requests

# general purpose
import subprocess
import glob
import os
import re

## Settings and information on the data

In [3]:
# general variables
path = os.getcwd() # current working directory
descriptive_suffix = "txt"

In [4]:
# hourly data: relevant information on the other data (web link, tags)
out_path = "../data/weather/weather-hourly/"

list_urls = [
    "https://opendata.dwd.de/climate_environment/CDC/observations_germany/climate/hourly/sun/recent/",
    "https://opendata.dwd.de/climate_environment/CDC/observations_germany/climate/hourly/sun/historical/",

    "https://opendata.dwd.de/climate_environment/CDC/observations_germany/climate/hourly/cloudiness/recent/",
    "https://opendata.dwd.de/climate_environment/CDC/observations_germany/climate/hourly/cloudiness/historical/",
    "https://opendata.dwd.de/climate_environment/CDC/observations_germany/climate/hourly/cloud_type/recent/",
    "https://opendata.dwd.de/climate_environment/CDC/observations_germany/climate/hourly/cloud_type/historical/",
    
    "https://opendata.dwd.de/climate_environment/CDC/observations_germany/climate/hourly/visibility/recent/",
    "https://opendata.dwd.de/climate_environment/CDC/observations_germany/climate/hourly/visibility/historical/",

    "https://opendata.dwd.de/climate_environment/CDC/observations_germany/climate/hourly/extreme_wind/recent/",
    "https://opendata.dwd.de/climate_environment/CDC/observations_germany/climate/hourly/extreme_wind/historical/",
    "https://opendata.dwd.de/climate_environment/CDC/observations_germany/climate/hourly/wind/recent/",
    "https://opendata.dwd.de/climate_environment/CDC/observations_germany/climate/hourly/wind/historical/",
    "https://opendata.dwd.de/climate_environment/CDC/observations_germany/climate/hourly/wind_synop/recent/",
    "https://opendata.dwd.de/climate_environment/CDC/observations_germany/climate/hourly/wind_synop/historical/",

    "https://opendata.dwd.de/climate_environment/CDC/observations_germany/climate/hourly/weather_phenomena/recent/",
    "https://opendata.dwd.de/climate_environment/CDC/observations_germany/climate/hourly/weather_phenomena/historical/",

    "https://opendata.dwd.de/climate_environment/CDC/observations_germany/climate/hourly/precipitation/recent/",
    "https://opendata.dwd.de/climate_environment/CDC/observations_germany/climate/hourly/precipitation/historical/",

    # more weather measurements
    "https://opendata.dwd.de/climate_environment/CDC/observations_germany/climate/hourly/dew_point/recent/",
    "https://opendata.dwd.de/climate_environment/CDC/observations_germany/climate/hourly/dew_point/historical/",

    "https://opendata.dwd.de/climate_environment/CDC/observations_germany/climate/hourly/moisture/recent/",
    "https://opendata.dwd.de/climate_environment/CDC/observations_germany/climate/hourly/moisture/historical/",

    "https://opendata.dwd.de/climate_environment/CDC/observations_germany/climate/hourly/air_temperature/recent/",
    "https://opendata.dwd.de/climate_environment/CDC/observations_germany/climate/hourly/air_temperature/historical/",

    "https://opendata.dwd.de/climate_environment/CDC/observations_germany/climate/hourly/soil_temperature/recent/",
    "https://opendata.dwd.de/climate_environment/CDC/observations_germany/climate/hourly/soil_temperature/historical/",

    "https://opendata.dwd.de/climate_environment/CDC/observations_germany/climate/hourly/pressure/recent/",
    "https://opendata.dwd.de/climate_environment/CDC/observations_germany/climate/hourly/pressure/historical/",
]

list_data_tags = [
    "SD_sun_hourly_recent",
    "SD_sun_hourly_historical", 

    "N_cloudiness_recent",
    "N_cloudiness_historical",
    "CS_cloud_type_recent",
    "CS_cloud_type_historical",

    "VV_visibility_recent",
    "VV_visibility_historical",

    "FX_extreme_wind_recent",
    "FX_extreme_wind_historical",
    "FF_wind_recent",
    "FF_wind_historical",
    "F_wind_synopsis_recent",
    "F_wind_synopsis_historical",

    "WW_weather_phenomena_recent",
    "WW_weather_phenomena_historical",

    "RR_precipitation_recent",
    "RR_precipitation_historical",

    # more weather measurements
    "TD_dewpoint_recent",
    "TD_dewpoint_historical",

    "TF_moisture_recent",
    "TF_moisture_historical",

    "TU_temp_air_recent",
    "TU_temp_air_historical",

    "EB_temp_soil_recent",
    "EB_temp_soil_historical",

    "P0_pressure_recent",
    "P0_pressure_historical",
]

list_web_tags = [
    "SD",
    "SD",

    "N",
    "N",
    "CS",
    "CS",

    "VV",
    "VV",
    
    "FX",
    "FX",
    "FF",
    "FF",
    "F",
    "F",

    "WW",
    "WW",

    "RR",
    "RR",

    # more weather measurements
    "TD",
    "TD",

    "TF",
    "TF",

    "TU",
    "TU",

    "EB",
    "EB",

    "PO",
    "PO",
]

In [5]:
# daily data: relevant information on the other data (web link, tags)
list_urls_daily = [
    "https://opendata.dwd.de/climate_environment/CDC/observations_germany/climate/daily/kl/recent/",
    "https://opendata.dwd.de/climate_environment/CDC/observations_germany/climate/daily/kl/historical/",
    "https://opendata.dwd.de/climate_environment/CDC/observations_germany/climate/daily/weather_phenomena/recent/",
    "https://opendata.dwd.de/climate_environment/CDC/observations_germany/climate/daily/weather_phenomena/historical/",
    "https://opendata.dwd.de/climate_environment/CDC/observations_germany/climate/daily/more_weather_phenomena/recent/",
    "https://opendata.dwd.de/climate_environment/CDC/observations_germany/climate/daily/more_weather_phenomena/historical/",
]

list_data_tags_daily = [
    "KL_climate_recent_daily",
    "KL_climate_historical_daily",
    "phenomena_recent_daily",
    "phenomena_historical_daily",
    "RR_morephenomena_recent_daily",
    "RR_morephenomena_historical_daily",
]

list_web_tags_daily = [
    "KL",
    "KL",
    "x",
    "x",
    "RR",
    "RR",
]

In [6]:
# correction of space-separated summary text file
location_dict = {
    "Altheim,,Kreis,Biberach": "Altheim Kreis Biberach",
    "Annweiler,am,Trifels-Stein": "Annweiler am Trifels-Stein",
    "Annweiler,am,Trifels/Pfalz": "Annweiler am Trifels/Pfalz",
    "Arolsen-Landau,,Bad": "Bad Arolsen-Landau",
    "Arolsen-Neu,Berich": "Arolsen-Neu Berich",
    "Arolsen-Volkhardinghausen,,Bad": "Bad Arolsen-Volkhardinghausen",
    "Au,i.d.Hallertau-Günzenhausen": "Au i.d.Hallertau-Günzenhausen",
    "Augsburg (Sankt,Stephan)": "Augsburg (Sankt Stephan)",
    "Aura,im,Sinngrund": "Aura im Sinngrund",
    "Aßlar,Klein-Altenstädten": "Aßlar Klein-Altenstädten",
    "Badewitz,bei,Zerbst": "Badewitz bei Zerbst",
    "Battenberg-Hof,Karlsburg": "Battenberg-Hof Karlsburg",
    "Bayerfeld-Steckweiler,-Schmalfelderhof": "Bayerfeld-Steckweiler-Schmalfelderhof",
    "Bedburg-Weiler,Hohenholz": "Bedburg-Weiler Hohenholz",
    "Bellingen,,Bad": "Bad Bellingen",
    "Bentheim,,Bad": "Bad Bentheim",
    "Bergzabern,,Bad": "Bad Bergzabern",
    "Berka,,Bad (Flugplatz)": "Bad Berka (Flugplatz)",
    "Berleburg,,Bad": "Bad Berleburg",
    "Berleburg,,Bad-Stünzel": "Bad-Stünzel Berleburg",
    "Berlin,Brandenburg": "Berlin Brandenburg",
    "Berlin-Tegeler,Fliesstal": "Berlin-Tegeler Fliesstal",
    "Bertrich,,Bad": "Bad Bertrich",
    "Bevern,,Kr.,Holzminden": "Bevern Kr. Holzminden",
    "Biberach,an,der,Riß-Bergerhausen": "Biberach an der Riß-Bergerhausen",
    "Bibra,,Bad-Altenroda": "Bad Bibra-Altenroda",
    "Blankenburg,,Bad": "Bad Blankenburg",
    "Boll,,Bad (KKst)": "Bad Boll (KKst)",
    "Boll,,Bad (Kläranl.)": "Bad Boll (Kläranl.)",
    "Borken,in,Westfalen": "Borken in Westfalen",
    "Bretten,,Kreis,Karlsruhe": "Bretten Kreis Karlsruhe",
    "Bruchweiler,,Kr.,Birkenfeld": "Bruchweiler Kr. Birkenfeld",
    "Brückenau,,Bad": "Bad Brückenau",
    "Buchen,,Kr.,Neckar": "Buchen Kr. Neckar",
    "Camberg,,Bad": "Bad Camberg",
    "Cölbe,,Kr.,Marburg-Biedenkopf": "Cölbe Kr. Marburg-Biedenkopf",
    "Darmstadt-Botanischer,Garten": "Darmstadt-Botanischer Garten",
    "Darßer,Ort (SWN)": "Darßer Ort (SWN)",
    "Deisenhofen,,Kreis,München": "Deisenhofen Kreis München",
    "Doberan,,Bad-Heiligendamm": "Doberan Bad-Heiligendamm",
    "Dortmund/Oespeler,Bach": "Dortmund/Oespeler Bach",
    "Drei,Gleichen-Mühlberg": "Drei Gleichen-Mühlberg",
    "Driburg,,Bad": "Bad Driburg",
    "Dürkheim,,Bad": "Bad Dürkheim",
    "Dürkheim,,Bad-Trift": "Bad Dürkheim-Trift",
    "Dürrenberg,,Bad": "Bad Dürrenberg",
    "Dürrheim,,Bad": "Bad Dürrheim",
    "Eging,am,See-Burgstall": "Eging am See-Burgstall",
    "Eging,am,See-Rohrbachholz": "Eging am See-Rohrbachholz",
    "Elster,,Bad-Sohl": "Bad-Sohl Elster",
    "Ems,,Bad": "Bad Ems",
    "Essen-Brockhausen,,Bad": "Bad Essen-Brockhausen",
    "FES,Weser": "FES Weser",
    "Falkenberg,Kr.Rottal-Inn": "Falkenberg Kr.Rottal-Inn",
    "Fallingbostel,,Bad": "Bad Fallingbostel",
    "Feilnbach,Bad": "Bad Feilnbach",
    "Forschungsplattform,Nordsee": "Forschungsplattform Nordsee",
    "Frankenhausen,,Bad/Kyffhäuser": "Bad Frankenhausen/Kyffhäuser",
    "Frankfurt (Henninger,Turm)": "Frankfurt (Henninger Turm)",
    "Freiburg,im,Breisgau-Herdern": "Freiburg im Breisgau-Herdern",
    "Freyung,vorm,Wald": "Freyung vorm Wald",
    "Fritzlar-Kasseler,Warte": "Fritzlar-Kasseler Warte",
    "Gehlberg,Glöckchen,im,Tal": "Gehlberg Glöckchen im Tal",
    "Gernrode (Bremer,Teich)": "Gernrode (Bremer Teich)",
    "Gierstädt,,Kreis,Gotha": "Gierstädt Kreis Gotha",
    "Glees/Laacher,See": "Glees/Laacher See",
    "Gollentaler,Grund (HRB)": "Gollentaler Grund (HRB)",
    "Gottleuba,,Bad": "Bad Gottleuba",
    "Gottleuba,,Bad/Osterzgebirge": "Bad Gottleuba/Osterzgebirge",
    "Grabow (Kläranlage,Fahlenkamp)": "Grabow (Kläranlage Fahlenkamp)",
    "Greifswalder,Oie": "Greifswalder Oie",
    "Griesheim,b.,Darmstadt": "Griesheim b. Darmstadt",
    "Grosser,Falkenstein": "Grosser Falkenstein",
    "Grosser,Inselsberg": "Grosser Inselsberg",
    "Groß,Berßen": "Groß Berßen",
    "Groß,Kiesow-Schlagtow": "Groß Kiesow-Schlagtow",
    "Groß,Kreutz-Krielow": "Groß Kreutz-Krielow",
    "Groß,Lukow": "Groß Lukow",
    "Groß,Lüsewitz": "Groß Lüsewitz",
    "Groß,Wittensee": "Groß Wittensee",
    "Großer,Arber": "Großer Arber",
    "Grund,,Bad (Erzbergwerk)": "Bad Grund (Erzbergwerk)",
    "Grund,,Bad": "Bad Grund",
    "Gräfendorf,Kr.Main-Spessart (Kläranlage)": "Gräfendorf Kr.Main-Spessart (Kläranlage)",
    "Gschwend,,Kr.,Ostalb": "Gschwend Kr. Ostalb",
    "Hallig,Hooge": "Hallig Hooge",
    "Hamburg (Deutsche,Seewarte)": "Hamburg (Deutsche Seewarte)",
    "Hamburg-Botanischer,Garten": "Hamburg-Botanischer Garten",
    "Hamburg-Sankt,Pauli": "Hamburg-Sankt Pauli",
    "Harth-Pöllnitz,Neundorf": "Harth-Pöllnitz Neundorf",
    "Harzburg,,Bad": "Bad Harzburg",
    "Haslach,im,Kinzigtal": "Haslach im Kinzigtal",
    "Hecklingen-Groß,Börnecke": "Hecklingen-Groß Börnecke",
    "Heiligenstadt,,Heilbad-Kalteneber": "Heiligenstadt Heilbad-Kalteneber",
    "Helse,,Kr.,Dithmarschen": "Helse Kr. Dithmarschen",
    "Herrenalb,,Bad": "Bad Herrenalb",
    "Hersfeld,,Bad": "Bad Hersfeld",
    "Hessisch,Lichtenau-Fürstenhagen": "Hessisch Lichtenau-Fürstenhagen",
    "Hildesheim,Flugplatz": "Hildesheim Flugplatz",
    "Hohe,Börde-Schackensleben": "Hohe Börde-Schackensleben",
    "Holzhausen,a.d.,Haide": "Holzhausen a.d. Haide",
    "Holzheim,bei,Diez": "Holzheim bei Diez",
    "Homburg,,Bad (Filterwerk)": "Bad Homburg (Filterwerk)",
    "Hoyerswerda,Kr.,Bautzen": "Hoyerswerda Kr. Bautzen",
    "Jachenau/Tölzer,Land": "Jachenau/Tölzer Land",
    "Kahler,Asten": "Kahler Asten",
    "Kaltenborn,,Hohe,Acht": "Kaltenborn Hohe Acht",
    "Kastl,,Kreis,Amberg-Sulzbach": "Kastl Kreis Amberg-Sulzbach",
    "Kell,am,See": "Kell am See",
    "Kerpen-Haus,Forst": "Kerpen-Haus Forst",
    "Kirchberg,,Rhein-Hunsrück-Kreis": "Kirchberg Rhein-Hunsrück-Kreis",
    "Kirchberg/Niederbayern,-Zell": "Kirchberg/Niederbayern-Zell",
    "Kirchdorf,,Kreis,Diepholz": "Kirchdorf Kreis Diepholz",
    "Kissingen,,Bad": "Bad Kissingen",
    "Kißlegg,,Kr.,Ravensburg": "Kißlegg Kr. Ravensburg",
    "Klein,Rönnau": "Klein Rönnau",
    "Klein,Wanzleben": "Klein Wanzleben",
    "Kleiner,Feldberg/Taunus": "Kleiner Feldberg/Taunus",
    "Kleiner,Inselsberg": "Kleiner Inselsberg",
    "Kleinich,,Kr.,Bernkastel-Wittlich": "Kleinich Kr. Bernkastel-Wittlich",
    "Klitzschen,bei,Torgau": "Klitzschen bei Torgau",
    "Klosterlausnitz,,Bad": "Bad Klosterlausnitz",
    "Kohlgrub,,Bad (A)": "Bad Kohlgrub (A)",
    "Kohlgrub,,Bad (Rosshof)": "Bad Kohlgrub (Rosshof)",
    "Kohlgrub,,Bad": "Bad Kohlgrub",
    "Kremmen-Groß,Ziethen": "Kremmen-Groß Ziethen",
    "Kreuznach,,Bad": "Bad Kreuznach",
    "Krozingen,,Bad": "Bad Krozingen",
    "Kubschütz,,Kr.,Bautzen": "Kubschütz Kr. Bautzen",
    "Köln-Botanischer,Garten": "Köln-Botanischer Garten",
    "Königsbach-Stein,,Enzkreis": "Königsbach-Stein Enzkreis",
    "Königshofen,,Bad": "Bad Königshofen",
    "Kösen,,Bad": "Bad Kösen",
    "Lage,,Kreis,Lippe-Hörste": "Lage Kreis Lippe-Hörste",
    "Langen-Holßel,,Kreis,Cuxhaven": "Langen-Holßel Kreis Cuxhaven",
    "Langensalza,,Bad": "Bad Langensalza",
    "Lauchstädt,,Bad": "Bad Lauchstädt",
    "Lauterberg,,Bad (A)": "Bad Lauterberg (A)",
    "Lauterberg,Bad-Bartolfelde": "Bad Lauterberg-Bartolfelde",
    "Lehesten/Thüringer,Wald": "Lehesten/Thüringer Wald",
    "Leipzig (Kläranlage,Rosental)": "Leipzig (Kläranlage Rosental)",
    "Leuchtturm,Alte,Weser": "Leuchtturm Alte Weser",
    "Leuchtturm,Kiel": "Leuchtturm Kiel",
    "Liebenstein,,Bad": "Bad Liebenstein",
    "Liebenzell,,Bad": "Bad Liebenzell",
    "Lippspringe,,Bad": "Bad Lippspringe",
    "List,auf,Sylt": "List auf Sylt",
    "Lobenstein,,Bad": "Bad Lobenstein",
    "Malente,,Bad-Gremsmühlen": "Malente Bad-Gremsmühlen",
    "Malk,Göhren": "Malk Göhren",
    "Marienberg,,Bad": "Bad Marienberg",
    "Marklkofen (Betriebsstelle,Vilstalsee)": "Marklkofen (Betriebsstelle Vilstalsee)",
    "Markt,Bibart": "Markt Bibart",
    "Markt,Erlbach-Hagenhofen": "Markt Erlbach-Hagenhofen",
    "Markt,Erlbach-Mosbach": "Markt Erlbach-Mosbach",
    "Marner,Deich": "Marner Deich",
    "Mehring,,Kr.,Altötting-Niederholz": "Mehring Kr. Altötting-Niederholz",
    "Meinberg,,Bad": "Bad Meinberg",
    "Mergentheim,,Bad-Neunkirchen": "Bad Mergentheim-Neunkirchen",
    "Moers (Klever,Strasse)": "Moers (Klever Strasse)",
    "Moos,Kr.,Deggendorf-Maxmühle": "Moos Kr. Deggendorf-Maxmühle",
    "Muskau,,Bad": "Bad Muskau",
    "Mühlhausen,,Kr.,Schweinfurt": "Mühlhausen Kr. Schweinfurt",
    "Mülheim-Kärlich,,Kr.,Mayen-Koblenz": "Mülheim-Kärlich Kr. Mayen-Koblenz",
    "München-Botanischer,Garten": "München-Botanischer Garten",
    "Münder,,Bad": "Bad Münder",
    "Münster,am,Stein,,Bad": "Bad Münster am Stein",
    "Münstereifel,,Bad-Eicherscheid": "Bad Münstereifel-Eicherscheid",
    "Münstermaifeld,,Kr.,Mayen-Koblenz": "Münstermaifeld Kr. Mayen-Koblenz",
    "Nauheim,,Bad": "Bad Nauheim",
    "Neckarwestheim,KKW": "Neckarwestheim KKW",
    "Neu,Madlitz": "Neu Madlitz",
    "Neuenahr,,Bad-Ahrweiler": "Bad Neuenahr-Ahrweiler",
    "Neuhaus,am,Rennweg": "Neuhaus am Rennweg",
    "Neuhausen,ob,Eck": "Neuhausen ob Eck",
    "Neuhausen,ob,Eck-Unterschwandorf": "Neuhausen ob Eck-Unterschwandorf",
    "Neukirchen,beim,Heiligen,Blut": "Neukirchen beim Heiligen Blut",
    "Neukirchen/Oberpfalz,-Haid": "Neukirchen/Oberpfalz-Haid",
    "Neumarkt-Sankt,Veit (Kläranlage)": "Neumarkt-Sankt Veit (Kläranlage)",
    "Neunburg,v.,Wald-Eixendorf (Seemeister)": "Neunburg v. Wald-Eixendorf (Seemeister)",
    "Neuruppin-Alt,Ruppin": "Neuruppin-Alt Ruppin",
    "Neuruppin-Gühlen,Glienicke": "Neuruppin-Gühlen Glienicke",
    "Neustadt,,Bad": "Bad Neustadt",
    "Neustadt,am,Kulm-Filchendorf": "Neustadt am Kulm-Filchendorf",
    "Neustadt,am,Rübenberge": "Neustadt am Rübenberge",
    "Neustadt,bei,Coburg (Kläranlage)": "Neustadt bei Coburg (Kläranlage)",
    "Nordseeboje,2": "Nordseeboje 2",
    "Nordseeboje,3": "Nordseeboje 3",
    "Nümbrecht,auf,dem,Lindchen": "Nümbrecht auf dem Lindchen",
    "Obere,Firstalm/Schlierseer,Berge": "Obere Firstalm/Schlierseer Berge",
    "Oberharz,am,Brocken-Stiege": "Oberharz am Brocken-Stiege",
    "Oppenau,Oberes,Renchtal": "Oppenau Oberes Renchtal",
    "Oppenheim/,Rhein": "Oppenheim/ Rhein",
    "Ostheim,v.d.,Rhön": "Ostheim v.d. Rhön",
    "Philippsburg,KKW": "Philippsburg KKW",
    "Plau,am,See": "Plau am See",
    "Polch,,Kr.,Mayen-Koblenz": "Polch Kr. Mayen-Koblenz",
    "Querfurt-Mühle,Lodersleben": "Querfurt-Mühle Lodersleben",
    "Quickborn (Kurzer,Kamp)": "Quickborn (Kurzer Kamp)",
    "Rain,am,Lech-Wallerdorf": "Rain am Lech-Wallerdorf",
    "Rappenau,,Bad": "Bad Rappenau",
    "Rauschberg,bei,Ruhpolding": "Rauschberg bei Ruhpolding",
    "Reichenhall,,Bad": "Bad Reichenhall",
    "Reit,im,Winkl (Tirolerstr.)": "Reit im Winkl (Tirolerstr.)",
    "Reit,im,Winkl": "Reit im Winkl",
    "Renningen-Ihinger,Hof": "Renningen-Ihinger Hof",
    "Rheinberg (Alte,Landstrasse)": "Rheinberg (Alte Landstrasse)",
    "Rippoldsau,,Bad": "Bad Rippoldsau",
    "Rot,am,See": "Rot am See",
    "Rot,an,der,Rot-Buch": "Rot an der Rot-Buch",
    "Roth,bei,Nürnberg": "Roth bei Nürnberg",
    "Roth,bei,Prüm": "Roth bei Prüm",
    "Rothenburg,ob,der,Tauber": "Rothenburg ob der Tauber",
    "Rothenfelde,,Bad": "Bad Rothenfelde",
    "Rothsee,bei,Allersberg": "Rothsee bei Allersberg",
    "Röhrigshof,bei,Schlüchtern": "Röhrigshof bei Schlüchtern",
    "Saarbrücken-Sankt,Johann": "Saarbrücken-Sankt Johann",
    "Sachsa,,Bad": "Bad Sachsa",
    "Salzuflen,,Bad": "Bad Salzuflen",
    "Salzungen,,Bad": "Bad Salzungen",
    "Salzungen,,Bad-Gräfen-Nitzendorf": "Bad Salzungen-Gräfen-Nitzendorf",
    "Sankt,Blasien": "Sankt Blasien",
    "Sankt,Egidien-Kuhschnappel": "Sankt Egidien-Kuhschnappel",
    "Sankt,Englmar": "Sankt Englmar",
    "Sankt,Michaelisdonn": "Sankt Michaelisdonn",
    "Sankt,Märgen": "Sankt Märgen",
    "Sankt,Peter": "Sankt Peter",
    "Sankt,Wendel-Hof": "Sankt Wendel-Hof",
    "Sankt,Wendel-Urweiler": "Sankt Wendel-Urweiler",
    "Sassendorf,,Bad-Beusingsen": "Bad Sassendorf-Beusingsen",
    "Sassendorf,,Bad-Ostinghausen": "Bad Sassendorf-Ostinghausen",
    "Saulgau,Bad": "Bad Saulgau",
    "Schiltach/,Kinzig": "Schiltach/ Kinzig",
    "Schkeuditz/Weiße,Elster": "Schkeuditz/Weiße Elster",
    "Schloßvippach,,Kreis,Sömmerda": "Schloßvippach Kreis Sömmerda",
    "Schlüchtern-Kloster,Gomfritz": "Schlüchtern-Kloster Gomfritz",
    "Schlüsselfeld-Hohn,am,Berg": "Schlüsselfeld-Hohn am Berg",
    "Schmalkalden,,Kurort": "Schmalkalden Kurort",
    "Schmiedeberg,,Bad": "Bad Schmiedeberg",
    "Schorfheide-Groß,Schönebeck": "Schorfheide-Groß Schönebeck",
    "Schwaigern-Stetten,am,Heuchelberg": "Schwaigern-Stetten am Heuchelberg",
    "Schwalbach,,Bad": "Bad Schwalbach",
    "Schwartau,Bad,-Groß,Parin": "Bad Schwartau-Groß Parin",
    "Schwarze,Pumpe": "Schwarze Pumpe",
    "Schwenningen,,Kreis,Sigmaringen": "Schwenningen Kreis Sigmaringen",
    "Schwäbisch,Gmünd (Wind)": "Schwäbisch Gmünd (Wind)",
    "Schwäbisch,Gmünd-Strassdorf": "Schwäbisch Gmünd-Strassdorf",
    "Schwäbisch,Gmünd-Weiler": "Schwäbisch Gmünd-Weiler",
    "Schwäbisch,Hall-Bibersfeld": "Schwäbisch Hall-Bibersfeld",
    "Schwäbisch,Hall-Wielandsweiler": "Schwäbisch Hall-Wielandsweiler",
    "Schäftlarn-Kloster,Schäftlarn": "Schäftlarn-Kloster Schäftlarn",
    "Schömberg,,Kr.,Calw": "Schömberg Kr. Calw",
    "Seegebiet,Mansfelder,Land-Dederstedt": "Seegebiet Mansfelder Land-Dederstedt",
    "Segeberg,,Bad": "Bad Segeberg",
    "Selb/Oberfranken (Ernst,Reuter,St": "Selb/Oberfranken (Ernst Reuter St",
    "Simbach,am,Inn-Grub": "Simbach am Inn-Grub",
    "Soden,Bad-Salmünster (Kläranlage)": "Soden Bad-Salmünster (Kläranlage)",
    "Sooden-Allendorf,,Bad": "Bad Sooden-Allendorf",
    "St.,Tönis": "St. Tönis",
    "Staffelstein,,Bad-Stublang": "Bad Staffelstein-Stublang",
    "Steben,,Bad": "Bad Steben",
    "Steinau,,Kr.,Cuxhaven": "Steinau Kr. Cuxhaven",
    "Straußfurt,,Kreis,Sömmerda": "Straußfurt Kreis Sömmerda",
    "Stuttgart (Schnarrenberg,Aero)": "Stuttgart (Schnarrenberg Aero)",
    "Suderode,,Bad": "Bad Suderode",
    "Sulzdorf,an,der,Lederhecke": "Sulzdorf an der Lederhecke",
    "Säckingen,,Bad (Bergseestr.)": "Bad Säckingen (Bergseestr.)",
    "Säckingen,,Bad/,Rhein": "Bad Säckingen/ Rhein",
    "Tabarz/Thüringer,Wald": "Tabarz/Thüringer Wald",
    "Timmendorfer,Strand": "Timmendorfer Strand",
    "Torfhaus,im,Solling": "Torfhaus im Solling",
    "Tornau,bei,Stendal": "Tornau bei Stendal",
    "Tölz,,Bad": "Bad Tölz",
    "Tönisvorst-St.,Tönis": "Tönisvorst-St. Tönis",
    "Tübingen (Botanischer,Garten)": "Tübingen (Botanischer Garten)",
    "UFS,Deutsche,Bucht": "UFS Deutsche Bucht",
    "UFS,Elbe,1": "UFS Elbe 1",
    "UFS,TW,Ems": "UFS TW Ems",
    "Urach,,Bad": "Bad Urach",
    "Urach,,Bad/Erms": "Bad Urach/Erms",
    "Ursensollen (Hohenburger,Str.)": "Ursensollen (Hohenburger Str.)",
    "Vaihingen/,Enz": "Vaihingen/ Enz",
    "Vilbel,,Bad-Dortelweil": "Bad Vilbel-Dortelweil",
    "Vöhl-Hof,Lauterbach": "Vöhl-Hof Lauterbach",
    "Waging,am,See": "Waging am See",
    "Waging,am,See-Schnöbling": "Waging am See-Schnöbling",
    "Wahnsdorf,bei,Dresden": "Wahnsdorf bei Dresden",
    "Waldhof (Lüneburger,Heide,UBA)": "Waldhof (Lüneburger Heide UBA)",
    "Waldhäuser (National,Park)": "Waldhäuser (National Park)",
    "Waldsee,,Bad-Reute": "Bad Waldsee-Reute",
    "Waldshut,KKW": "Waldshut KKW",
    "Wanzleben-Börde,/,Klein,Germersleben": "Wanzleben-Börde/Klein Germersleben",
    "Weidenbach,,Kr.Ansbach": "Weidenbach Kr.Ansbach",
    "Weiding,,Kreis,Cham-Dalking": "Weiding Kreis Cham-Dalking",
    "Weingarten,,Kr.,Ravensburg": "Weingarten Kr. Ravensburg",
    "Weisen,bei,Wittenberge": "Weisen bei Wittenberge",
    "Wendisch,Evern": "Wendisch Evern",
    "Wiersdorf/Stausee,Bitburg": "Wiersdorf/Stausee Bitburg",
    "Wildbad,,Bad-Calmbach": "Bad Wildbad-Calmbach",
    "Wildbad,,Bad-Sommerberg": "Bad Wildbad-Sommerberg",
    "Wildungen,,Bad": "Bad Wildungen",
    "Wildungen,,Bad-Braunau": "Bad Wildungen-Braunau",
    "Windsheim,,Bad": "Bad Windsheim",
    "Winterbach,,Rems-Murr-Kreis": "Winterbach Rems-Murr-Kreis",
    "Wittlich,,Kreisstadt": "Wittlich Kreisstadt",
    "Wittstock-Rote,Mühle": "Wittstock-Rote Mühle",
    "Zemmer (Forsthaus,Mülchen)": "Zemmer (Forsthaus Mülchen)",

    "Abbach,Bad-Dünzling": "Bad Abbach-Dünzling",
    "Adelholzen,,Bad": "Bad Adelholzen",
    "Ahlen,in,Westfalen": "Ahlen in Westfalen",
    "Aibling,,Bad-Ellmosen": "Bad Aibling-Ellmosen",
    "Algermissen-Groß,Lobke": "Algermissen-Groß Lobke",
    "Alt,Krenzlin-Krenzliner,Hütte": "Alt Krenzlin-Krenzliner Hütte",
    "Alt,Madlitz": "Alt Madlitz",
    "Alt,Zeschdorf": "Alt Zeschdorf",
    "Altena,in,Westfalen": "Altena in Westfalen",
    "Althütte,bei,Waldmünchen": "Althütte bei Waldmünchen",
    "An,der,Poststraße-Braunsroda": "An der Poststraße-Braunsroda",
    "Aspach-Allmersbach,am,Weinberg": "Aspach-Allmersbach am Weinberg",
    "Au,am,Rhein": "Au am Rhein",
    "Bad Berleburg (Alte,Warte)": "Bad Berleburg (Alte Warte)",
    "Bad Münder-Klein,Süntel": "Bad Münder-Klein Süntel",
    "Barßel-Loher,Ostmark": "Barßel-Loher Ostmark",
    "Bayerisch,Eisenstein": "Bayerisch Eisenstein",
    "Bayersoien,,Bad": "Bad Bayersoien",
    "Bechhofen/Mittelfranken,-Voggendorf": "Bechhofen/Mittelfranken-Voggendorf",
    "Belleben-Haus,Zeitz": "Belleben-Haus Zeitz",
    "Belsdorf,bei,Behnsdorf": "Belsdorf bei Behnsdorf",
    "Belzig,,Bad": "Bad Belzig",
    "Bergen-Nindorf,,Kreis,Celle": "Bergen-Nindorf Kreis Celle",
    "Bergisch,Gladbach,-Refrath": "Bergisch Gladbach-Refrath",
    "Berka,,Bad": "Bad Berka",
    "Berlin-Lichterfelde,Ost": "Berlin-Lichterfelde Ost",
    "Berlin-Marzahn,,Apw": "Berlin-Marzahn Apw",
    "Bernau,,Kreis,Rosenheim": "Bernau Kreis Rosenheim",
    "Bernbeuren,a.,Auerberg": "Bernbeuren a. Auerberg",
    "Berneck,,Bad": "Bad Berneck",
    "Bernried/Niederbayern,-Buchet": "Bernried/Niederbayern-Buchet",
    "Bernsdorf,,Krs.,Kamenz": "Bernsdorf Krs. Kamenz",
    "Bernstadt,a.,d.,Eigen-Kemnitz": "Bernstadt a. d. Eigen-Kemnitz",
    "Beuren,,Kreis,Trier-Saarburg": "Beuren Kreis Trier-Saarburg",
    "Bevensen,,Bad": "Bad Bevensen",
    "Bibra,,Bad": "Bad Bibra",
    "Bielefeld (Stadtreinigungsamt,)": "Bielefeld (Stadtreinigungsamt )",
    "Bingen,,Kreis,Sigmaringen": "Bingen Kreis Sigmaringen",
    "Birnbach,,Bad": "Bad Birnbach",
    "Bischofsgrün (Hohe,Reuth)": "Bischofsgrün (Hohe Reuth)",
    "Bissingen,,Kreis,Dillingen": "Bissingen Kreis Dillingen",
    "Blumberg,,Kreis,Barnim": "Blumberg Kreis Barnim",
    "Bockhorn/Oberbayern,-Grünbach": "Bockhorn/Oberbayern-Grünbach",
    "Bocklet,,Bad": "Bad Bocklet",
    "Bodenfelde (Forsthaus,Winnefeld)": "Bodenfelde (Forsthaus Winnefeld)",
    "Bodenteich,,Bad": "Bad Bodenteich",
    "Boll,,Bad": "Bad Boll",
    "Boppard-Salzig,,Bad": "Bad Boppard-Salzig",
    "Borstel,über,Bad,Oldesloe": "Bad Borstel über Oldesloe",
    "Brambach,,Bad,Raun-Gürth": "Bad Brambach Raun-Gürth",
    "Bramstedt,,Bad-Bimöhlen": "Bad Bramstedt-Bimöhlen",
    "Breitenbrunn/Oberpfalz,-Gimpertshausen": "Breitenbrunn/Oberpfalz-Gimpertshausen",
    "Breitungen/Werra,1": "Breitungen/Werra 1",
    "Bremen (Bayernstraße,)": "Bremen (Bayernstraße )",
    "Bremen (Ritterhuder,Heerstraße)": "Bremen (Ritterhuder Heerstraße)",
    "Bremen (Warturmer,Heerstraße)": "Bremen (Warturmer Heerstraße)",
    "Briesen,,Kreis,Cottbus": "Briesen Kreis Cottbus",
    "Bruchhausen,Vilsen,Berxen": "Bruchhausen Vilsen Berxen",
    "Buch,am,Wald-Schönbronn": "Buch am Wald-Schönbronn",
    "Buchau,,Bad": "Bad Buchau",
    "Buchholz (-Moor),,Kreis,Dithmarschen": "Buchholz (-Moor) Kreis Dithmarschen",
    "Burg,,Kreis,Dithmarschen": "Burg Kreis Dithmarschen",
    "Burgen,,Kreis,Mayen-Koblenz": "Burgen Kreis Mayen-Koblenz",
    "Börnicke,,Kreis,Havelland": "Börnicke Kreis Havelland",
    "Clausthal-Zellerfeld,-Buntenbock": "Clausthal-Zellerfeld-Buntenbock",
    "Clausthal-Zellerfeld,-Erbprinzentanne": "Clausthal-Zellerfeld-Erbprinzentanne",
    "Cloppenburg,in,Oldenburg": "Cloppenburg in Oldenburg",
    "Colberg,,Bad": "Bad Colberg",
    "Deisenhofen,bei,München": "Deisenhofen bei München",
    "Ditzenbach,,Bad": "Bad Ditzenbach",
    "Doberan,,Bad": "Bad Doberan",
    "Düben/Mulde,,Bad": "Bad Düben/Mulde",
    "Ebersdorf,,Kreis,Coburg": "Ebersdorf Kreis Coburg",
    "Eckelsheim (Villa,Bäder)": "Eckelsheim (Villa Bäder)",
    "Ehingen,,Kreis,Ansbach": "Ehingen Kreis Ansbach",
    "Elend (Kalte,Bode)": "Elend (Kalte Bode)",
    "Ellern (Forsthaus,Thiergarten,)": "Ellern (Forsthaus Thiergarten )",
    "Endbach,,Bad-Wommelshaus": "Bad Endbach-Wommelshaus",
    "Endorf,,Bad-Jolling": "Bad Endorf-Jolling",
    "Endorf,,Bad-Teisenham": "Bad Endorf-Teisenham",
    "Ensdorf/Oberpfalz,-Hirschwald": "Ensdorf/Oberpfalz-Hirschwald",
    "Eresing (Sankt,Ottilien)": "Eresing (Sankt Ottilien)",
    "Essen-Calhorn,,Kreis,Cloppenburg": "Essen-Calhorn Kreis Cloppenburg",
    "Falkenstein,,Kreis,Cham": "Falkenstein Kreis Cham",
    "Falkenstein/Weiße,Göltzsch": "Falkenstein/Weiße Göltzsch",
    "Feldkirchen-Westerham,-Vagen": "Feldkirchen-Westerham-Vagen",
    "Fischhausen,bei,Schliersee": "Fischhausen bei Schliersee",
    "Forst-Klein,Bademeusel": "Bad Forst-Kleinemeusel",
    "Frankenberg/Eder,-Schreufa": "Frankenberg/Eder-Schreufa",
    "Frankenberg/Eder,-Willersdorf": "Frankenberg/Eder-Willersdorf",
    "Freiburg,im,Breisgau (Hauptbahnhof)": "Freiburg im Breisgau (Hauptbahnhof)",
    "Freiburg,im,Breisgau-Ebnet": "Freiburg im Breisgau-Ebnet",
    "Freiburg,im,Breisgau-Haslach": "Freiburg im Breisgau-Haslach",
    "Freiburg,im,Breisgau-Mooswald": "Freiburg im Breisgau-Mooswald",
    "Freiburg,im,Breisgau-Sankt,Georgen": "Freiburg im Breisgau-Sankt Georgen",
    "Freiburg,im,Breisgau-Schlierberg": "Freiburg im Breisgau-Schlierberg",
    "Freienwalde/Oder,,Bad": "Bad Freienwalde/Oder",
    "Friedland-Groß,Schneen": "Friedland-Groß Schneen",
    "Friedland/Nieder,Lausitz": "Friedland/Nieder Lausitz",
    "Friedrichsbrunn,,Viktorshöhe": "Friedrichsbrunn Viktorshöhe",
    "Fronau,,Kreis,Cham": "Fronau Kreis Cham",
    "Furth,im,Wald": "Furth im Wald",
    "Fürstenzell-Höhenstadt,Bad": "Bad Fürstenzell-Höhenstadt",
    "Fürstlich,Drehna": "Fürstlich Drehna",
    "Füssing,Bad-Voglöd": "Bad Füssing-Voglöd",
    "Gager-Groß,Zicker": "Gager-Groß Zicker",
    "Gaggenau-Rotenfels,Bad": "Bad Gaggenau-Rotenfels",
    "Gandersheim,,Bad": "Bad Gandersheim",
    "Garmisch-Partenkirchen,-Eckbauer": "Garmisch-Partenkirchen-Eckbauer",
    "Garmisch-Partenkirchen,-Kaltenbrunn": "Garmisch-Partenkirchen-Kaltenbrunn",
    "Geislingen,an,der,Steige": "Geislingen an der Steige",
    "Graal-Müritz,,Seeheilbad": "Graal-Müritz Seeheilbad",
    "Griesbach,,Bad,im,Rottal-Kemading": "Bad Griesbach im Rottal-Kemading",
    "Groß,Brütz": "Groß Brütz",
    "Groß,Bölkow-Matersen": "Groß Bölkow-Matersen",
    "Groß,Dölln": "Groß Dölln",
    "Groß,Düben": "Groß Düben",
    "Groß,Ippener": "Groß Ippener",
    "Groß,Krankow-Klein,Krankow": "Groß Krankow-Klein Krankow",
    "Groß,Krankow-Käselow": "Groß Krankow-Käselow",
    "Groß,Neuendorf": "Groß Neuendorf",
    "Groß,Oesingen": "Groß Oesingen",
    "Groß,Quenstedt": "Groß Quenstedt",
    "Groß,Rodensleben": "Groß Rodensleben",
    "Groß,Schwarzlosen": "Groß Schwarzlosen",
    "Groß,Schwechten": "Groß Schwechten",
    "Großen,Luckow": "Großen Luckow",
    "Grund-Windhausen,,Bad": "Bad Grund-Windhausen",
    "Gutach,im,Breisgau-Bleibach": "Gutach im Breisgau-Bleibach",
    "Göhren,,Kreis,Mecklenburg-Strelitz": "Göhren Kreis Mecklenburg-Strelitz",
    "Güntersberge (Gut,Bärenrode)": "Güntersberge (Gut Bärenrode)",
    "Haag,,Kreis,Mühldorf": "Haag Kreis Mühldorf",
    "Hagen/Hasper,Bach": "Hagen/Hasper Bach",
    "Hanstedt,,Kreis,Uelzen,-Velgen": "Hanstedt Kreis Uelzen-Velgen",
    "Harthausen,,Kreis,Zollernalb": "Harthausen Kreis Zollernalb",
    "Hartheim,am,Rhein": "Hartheim am Rhein",
    "Hartmannsdorf,,Kreis,Oder-Spree": "Hartmannsdorf Kreis Oder-Spree",
    "Hartmannsdorf,,Kreis,Saale": "Hartmannsdorf Kreis Saale",
    "Hartmannsdorf,bei,Kirchberg": "Hartmannsdorf bei Kirchberg",
    "Harzgerode (Forsthaus,Scheerenstieg)": "Harzgerode (Forsthaus Scheerenstieg)",
    "Heidelberg (Kurhaus,Kohlhof)": "Heidelberg (Kurhaus Kohlhof)",
    "Hennigsdorf,b.,Berlin-Stolpe-Süd": "Hennigsdorf b. Berlin-Stolpe-Süd",
    "Heppenheim,,Kreis,Bergstraße": "Heppenheim Kreis Bergstraße",
    "Heringsdorf,,Seebad": "Heringsdorf Seebad",
    "Herne (Gräffstraße,)": "Herne (Gräffstraße )",
    "Hessisch,Lichtenau": "Hessisch Lichtenau",
    "Hessisch,Lichtenau-Hausen": "Hessisch Lichtenau-Hausen",
    "Hessisch,Oldendorf": "Hessisch Oldendorf",
    "Hindelang (Oberes,Ostrachtal)": "Hindelang (Oberes Ostrachtal)",
    "Hindelang-Oberdorf,,Bad": "Bad Hindelang-Oberdorf",
    "Hirschbach/Finstere,Erle": "Hirschbach/Finstere Erle",
    "Hofheim/Taunus,-Wallau": "Hofheim/Taunus-Wallau",
    "Hohen,Neuendorf": "Hohen Neuendorf",
    "Hohen,Pritz-Kukuk": "Hohen Pritz-Kukuk",
    "Hohenbrück-Neu,Schadow": "Hohenbrück-Neu Schadow",
    "Hohenfels,,Kr.Konstanz-Kalkofen": "Hohenfels Kr.Konstanz-Kalkofen",
    "Hoher,Meißner": "Hoher Meißner",
    "Holzkirchen/Oberbayern,-Leithen": "Holzkirchen/Oberbayern-Leithen",
    "Homburg,,Bad-Saalburg": "Bad Homburg-Saalburg",
    "Honnef,,Bad": "Bad Honnef",
    "Honnef,,Bad (Servatiushof)": "Bad Honnef (Servatiushof)",
    "Horn-Bad,Meinberg,-,Leopoldstal": "Horn-Bad Meinberg- Leopoldstal",
    "Horst,,Kreis,Steinburg": "Horst Kreis Steinburg",
    "Hude/Oldenburg,-Oberhausen": "Hude/Oldenburg-Oberhausen",
    "Höchst/Odenwald,-Hummetroth": "Höchst/Odenwald-Hummetroth",
    "Iburg-Glane,,Bad": "Bad Iburg-Glane",
    "Ilsede-Groß,Bülten": "Ilsede-Groß Bülten",
    "Jonsdorf,,Kurort": "Jonsdorf Kurort",
    "Kalkhorst-Groß,Schwansee": "Kalkhorst-Groß Schwansee",
    "Karlshafen,,Bad": "Bad Karlshafen",
    "Karow,,Kreis,Parchim": "Karow Kreis Parchim",
    "Kirchdorf,im,Wald": "Kirchdorf im Wald",
    "Kirchhundem-Kohlhagen,-Wirme": "Kirchhundem-Kohlhagen-Wirme",
    "Klein,Bennebek": "Klein Bennebek",
    "Klein,Nordende": "Klein Nordende",
    "Klein,Plasten": "Klein Plasten",
    "Klein,Ziethen": "Klein Ziethen",
    "Kraiburg,am,Inn": "Kraiburg am Inn",
    "Krakow,am,See": "Krakow am See",
    "Krauschwitz-Klein,Priebus": "Krauschwitz-Klein Priebus",
    "Königshütte/Harz (Überleitungssperre,)": "Königshütte/Harz (Überleitungssperre )",
    "Köstritz,,Bad": "Bad Köstritz",
    "Kühlungsborn,,Ostseebad": "Kühlungsborn Ostseebad",
    "Kühlungsborn,,Ostseebad1": "Kühlungsborn Ostseebad1",
    "Laar,,Kreis,Grafschaft,Bentheim": "Laar Kreis Grafschaft Bentheim",
    "Laasphe,,Bad": "Bad Laasphe",
    "Laasphe,,Bad-Hesselbach": "Bad Laasphe-Hesselbach",
    "Laasphe,,Bad-Rückershausen": "Bad Laasphe-Rückershausen",
    "Lage,,Kreis,Lippe": "Lage Kreis Lippe",
    "Langeln,Kreis,Wernigerode": "Langeln Kreis Wernigerode",
    "Langenlehsten,,Kreis,Lauenburg": "Langenlehsten Kreis Lauenburg",
    "Lausick,,Bad-Ebersbach": "Bad Lausick-Ebersbach",
    "Lausick,,Bad-Glasten": "Bad Lausick-Glasten",
    "Lauterberg,,Bad (Odertalsperre)": "Bad Lauterberg (Odertalsperre)",
    "Lengefeld,,Kreis,Weimar": "Lengefeld Kreis Weimar",
    "Leutenbach-Weiler,zum,Stein": "Leutenbach-Weiler zum Stein",
    "Lichtenau,in,Westfalen": "Lichtenau in Westfalen",
    "Lichtenau,in,Westfalen,-Blankenrode": "Lichtenau in Westfalen-Blankenrode",
    "Lichtenfels/Oberfranken,-Isling": "Lichtenfels/Oberfranken-Isling",
    "Lichtenfels/Oberfranken,-Seubelsdorf": "Lichtenfels/Oberfranken-Seubelsdorf",
    "Lohr/Main,-Ruppertshütten": "Lohr/Main-Ruppertshütten",
    "Lorch,,Kreis,Ostalb-Waldhausen": "Lorch Kreis Ostalb-Waldhausen",
    "Ludwigsburg,,Kr.Uckermark": "Ludwigsburg Kr.Uckermark",
    "Lutter,am,Barenberge": "Lutter am Barenberge",
    "Marbach,,Kreis,Haßberge": "Marbach Kreis Haßberge",
    "Marienheide (Kläranlage,Nord)": "Marienheide (Kläranlage Nord)",
    "Markt,Einersheim": "Markt Einersheim",
    "Markt,Erlbach-Wilhelmsgreuth": "Markt Erlbach-Wilhelmsgreuth",
    "Markt,Taschendorf,-Birkach": "Markt Taschendorf-Birkach",
    "Markt,Wald": "Markt Wald",
    "Marktschellenberg,-Ettenberg": "Marktschellenberg-Ettenberg",
    "Marschacht-Nieder,Marschacht": "Marschacht-Nieder Marschacht",
    "Meiningen,2": "Meiningen 2",
    "Metzingen,bei,Eldingen": "Metzingen bei Eldingen",
    "Michelau/Oberfranken,-Lettenreuth": "Michelau/Oberfranken-Lettenreuth",
    "Michelbach,an,der,Bilz": "Michelbach an der Bilz",
    "Muldenberg/Zwickauer,Mulde": "Muldenberg/Zwickauer Mulde",
    "Märkische,Heide-Dollgen": "Märkische Heide-Dollgen",
    "Mühlen,Eichsen": "Mühlen Eichsen",
    "München (Sankt,Bonifaz)": "München (Sankt Bonifaz)",
    "Münstereifel,,Bad": "Bad Münstereifel",
    "Münstereifel,,Bad-Houverath": "Bad Münstereifel-Houverath",
    "Nesseltal,bei,Bayrischzell": "Nesseltal bei Bayrischzell",
    "Neu,Poserin": "Neu Poserin",
    "Neu,Zauche": "Neu Zauche",
    "Neubrandenburg (Küssower,Str.)": "Neubrandenburg (Küssower Str.)",
    "Neuenhagen,bei": "Neuenhagen bei",
    "Neuenkirchen,,Kreis,Osnabrück": "Neuenkirchen Kreis Osnabrück",
    "Neuhof,,Kreis,Fulda": "Neuhof Kreis Fulda",
    "Neukirchen,b.,Heilg.,Blut": "Neukirchen b. Heilg. Blut",
    "Neukirchen-Balbini,-Meidenried": "Neukirchen-Balbini-Meidenried",
    "Neumarkt-Sankt,Veit/Rott": "Neumarkt-Sankt Veit/Rott",
    "Neunburg,vorm,Wald-Mitteraschau": "Neunburg vorm Wald-Mitteraschau",
    "Neunkirchen,,Kreis,Miltenberg": "Neunkirchen Kreis Miltenberg",
    "Neunkirchen,,Kreis,Siegen-Wittgenstein": "Neunkirchen Kreis Siegen-Wittgenstein",
    "Neustadt,,Kreis,Marburg-Biedenkopf": "Neustadt Kreis Marburg-Biedenkopf",
    "Neustadt,am,Rennsteig": "Neustadt am Rennsteig",
    "Neustadt,in,Holstein": "Neustadt in Holstein",
    "Neuweiler,,Kreis,Calw": "Neuweiler Kreis Calw",
    "Nidda-Ober,Lais": "Nidda-Ober Lais",
    "Nossentiner,Hütte": "Nossentiner Hütte",
    "Nürnberg (Germanisches,Museum)": "Nürnberg (Germanisches Museum)",
    "Oberharz,am,Brocken-Elend": "Oberharz am Brocken-Elend",
    "Oberharz,am,Brocken-Rübeland": "Oberharz am Brocken-Rübeland",
    "Oberharz,am,Brocken-Sorge": "Oberharz am Brocken-Sorge",
    "Oberhausen (Kaisergarten,)": "Oberhausen (Kaisergarten )",
    "Oberhof (Forsthaus,Sattelbach)": "Oberhof (Forsthaus Sattelbach)",
    "Oberndorf,am,Neckar": "Oberndorf am Neckar",
    "Oberried-Sankt,Wilhelm": "Oberried-Sankt Wilhelm",
    "Oberried-Sankt,Wilhelm (Forsthaus,)": "Oberried-Sankt Wilhelm (Forsthaus )",
    "Oberwiesenthal,,Kurort": "Oberwiesenthal Kurort",
    "Oebisfelde,,Buchhorst": "Oebisfelde Buchhorst",
    "Oeynhausen,,Bad": "Bad Oeynhausen",
    "Oldenburg,in,Holstein": "Oldenburg in Holstein",
    "Oldesloe,,Bad": "Bad Oldesloe",
    "Orb,,Bad": "Bad Orb",
    "Paderborn-Schloß,Neuhaus": "Paderborn-Schloß Neuhaus",
    "Pansfelde (Burg,Falkenstein,)": "Pansfelde (Burg Falkenstein )",
    "Pfaffenhofen,,Kreis,Heilbronn": "Pfaffenhofen Kreis Heilbronn",
    "Pinnow,Kreis,Prignitz": "Pinnow Kreis Prignitz",
    "Pinnow,Kreis,Spree-Neiße": "Pinnow Kreis Spree-Neiße",
    "Poppenhausen,,Kreis,Fulda": "Poppenhausen Kreis Fulda",
    "Porta,Westfalica-Barkhausen": "Porta Westfalica-Barkhausen",
    "Prerow,,Ostseebad": "Prerow Ostseebad",
    "Pyrmont,,Bad": "Bad Pyrmont",
    "Ragow,,Kreis,Dahme-Spreewald": "Ragow Kreis Dahme-Spreewald",
    "Ragow,,Kreis,Oberspreewald": "Ragow Kreis Oberspreewald",
    "Rahden-Preußisch,Ströhen": "Rahden-Preußisch Ströhen",
    "Rain,am,Lech": "Rain am Lech",
    "Ramsau,bei,Berchtesgaden": "Ramsau bei Berchtesgaden",
    "Rauhöd,bei,Schonstett": "Rauhöd bei Schonstett",
    "Rehberger,Grabenhaus": "Rehberger Grabenhaus",
    "Rehburg,,Bad": "Bad Rehburg",
    "Reinsdorf,,Kreis,Nebra": "Reinsdorf Kreis Nebra",
    "Reinsdorf,,Kreis,Teltow-Fläming": "Reinsdorf Kreis Teltow-Fläming",
    "Rerik,,Ostseebad": "Rerik Ostseebad",
    "Rietz,bei,Brandenburg": "Rietz bei Brandenburg",
    "Rimbach/Oberpfalz,-Hohenbogen": "Rimbach/Oberpfalz-Hohenbogen",
    "Rosbach,vor,der,Höhe,-Rodheim": "Rosbach vor der Höhe-Rodheim",
    "Rosengarten,,Kreis,Harburg": "Rosengarten Kreis Harburg",
    "Rot,an,der,Rot-Spindelwag": "Rot an der Rot-Spindelwag",
    "Rote,Kreuz": "Rote Kreuz",
    "Rotenburg/Fulda,-Seifertshausen": "Rotenburg/Fulda-Seifertshausen",
    "Rottenburg-Niedernau,,Bad": "Bad Rottenburg-Niedernau",
    "Rottenburg/Niederbayern,-Oberroning": "Rottenburg/Niederbayern-Oberroning",
    "Saarow-Pieskow,,Bad": "Bad Saarow-Pieskow",
    "Salzdetfurth,,Bad": "Bad Salzdetfurth",
    "Salzhausen,,Kreis,Harburg": "Salzhausen Kreis Harburg",
    "Salzschlirf,,Bad": "Bad Salzschlirf",
    "Sankt,Andreasberg": "Sankt Andreasberg",
    "Sankt,Andreasberg-Oderbrück": "Sankt Andreasberg-Oderbrück",
    "Sankt,Andreasberg-Oderhaus": "Sankt Andreasberg-Oderhaus",
    "Sankt,Augustin-Hangelar": "Sankt Augustin-Hangelar",
    "Sankt,Bernhard": "Sankt Bernhard",
    "Sankt,Georgen/Schwarzwald": "Sankt Georgen/Schwarzwald",
    "Sankt,Johann-Gächingen": "Sankt Johann-Gächingen",
    "Sankt,Michaelis": "Sankt Michaelis",
    "Sankt,Oswald-Riedlhütte": "Sankt Oswald-Riedlhütte",
    "Sankt,Wendel": "Sankt Wendel",
    "Saulgau,,Bad-Bolstern": "Bad Saulgau-Bolstern",
    "Schlangenbad-Hausen,vor,der,Höhe": "Schlangenbad-Hausen vor der Höhe",
    "Schmiedefeld,,Krs.Saalfeld": "Schmiedefeld Krs.Saalfeld",
    "Schmiedefeld,am,Rennsteig": "Schmiedefeld am Rennsteig",
    "Schotten-Breungeshain (,Jugendherberge)": "Schotten-Breungeshain ( Jugendherberge)",
    "Schussenried,,Bad-Olzreute": "Bad Schussenried-Olzreute",
    "Schwarzenbach,am,Wald (Döbraberg)": "Schwarzenbach am Wald (Döbraberg)",
    "Schwarzenbach,am,Wald-Rodeck": "Schwarzenbach am Wald-Rodeck",
    "Schweix,,Kr.,Südwestpfalz": "Schweix Kr. Südwestpfalz",
    "Schwäbisch,Hall (Adolf-Würth-Airport)": "Schwäbisch Hall (Adolf-Würth-Airport)",
    "Schöna,,Sächsische,Schweiz": "Schöna Sächsische Schweiz",
    "Schönberg,in,Holstein": "Schönberg in Holstein",
    "Schöneiche,bei": "Schöneiche bei",
    "Schönwalde,,Kreis,Dahme-Spremberg": "Schönwalde Kreis Dahme-Spremberg",
    "Schöppenstedt-Groß,Rode": "Schöppenstedt-Groß Rode",
    "Seebach,,Wartburgkreis": "Seebach Wartburgkreis",
    "Seedorf,,Kreis,Lüneburg": "Seedorf Kreis Lüneburg",
    "Seedorf,,Kreis,Segeberg,-Blomnath": "Seedorf Kreis Segeberg-Blomnath",
    "Seegebiet,Mansfelder,Land-Röblingen": "Seegebiet Mansfelder Land-Röblingen",
    "Siegsdorf-Maria,Eck": "Siegsdorf-Maria Eck",
    "Siptenfelde (Forsthaus,Uhlenstein)": "Siptenfelde (Forsthaus Uhlenstein)",
    "Soden,,Bad-Salmünster": "Bad Soden-Salmünster",
    "Sosa/Kleine,Bockau": "Sosa/Kleine Bockau",
    "Stavenhagen,,Reuterstadt": "Stavenhagen Reuterstadt",
    "Steinbach,am,Wald": "Steinbach am Wald",
    "Steinheim,,Kreis,Höxter": "Steinheim Kreis Höxter",
    "Stetten,,Kreis,Donnersberg": "Stetten Kreis Donnersberg",
    "Stockstadt,am,Rhein": "Stockstadt am Rhein",
    "Straß,bei,Geratskirchen": "Straß bei Geratskirchen",
    "Stromberg,,Kreis,Warendorf": "Stromberg Kreis Warendorf",
    "Suhl,,Nst": "Suhl Nst",
    "Sulza,,Bad-Eckolstädt": "Bad Sulza-Eckolstädt",
    "Söllingen,,Kr.,Helmstedt": "Söllingen Kr. Helmstedt",
    "Sülze,,Bad": "Bad Sülze",
    "Taunusstein-Eiserne,Hand": "Taunusstein-Eiserne Hand",
    "Teinach,,Bad-Zavelstein": "Bad Teinach-Zavelstein",
    "Tennstedt,,Bad": "Bad Tennstedt",
    "Tiefensee,,Kreis,Barnim": "Tiefensee Kreis Barnim",
    "Tiefensee,,Kreis,Delitzsch": "Tiefensee Kreis Delitzsch",
    "Uffing,am,Staffelsee-Schöffau": "Uffing am Staffelsee-Schöffau",
    "Vaihingen,an,der,Enz-Riet": "Vaihingen an der Enz-Riet",
    "Waldsee,,Bad-Dinnenried": "Bad Waldsee-Dinnenried",
    "Waltrop (im,Depot)": "Waltrop (im Depot)",
    "Wangerland-Oldorfer,Sietwendung": "Wangerland-Oldorfer Sietwendung",
    "Weil,am,Rhein-Haltingen": "Weil am Rhein-Haltingen",
    "Weil,der,Stadt": "Weil der Stadt",
    "Weil,im,Schönbuch": "Weil im Schönbuch",
    "Weilheim/Waldshut,-Bannholz": "Weilheim/Waldshut-Bannholz",
    "Weißbach,bei,Königsbrück": "Weißbach bei Königsbrück",
    "Weißig,am,Raschütz": "Weißig am Raschütz",
    "Wernberg-Köblitz,-Neunaigen": "Wernberg-Köblitz-Neunaigen",
    "Westendorf,,Kreis,Ostallgäu": "Westendorf Kreis Ostallgäu",
    "Wiesenburg,1": "Wiesenburg 1",
    "Wiessee,,Bad-Bauer,in,der,Au": "Bad Wiessee-Bauer in der Au",
    "Wildberg,,Kreis,Calw": "Wildberg Kreis Calw",
    "Willingen/Upland,-Eimelrod": "Willingen/Upland-Eimelrod",
    "Wilsnack,,Bad": "Bad Wilsnack",
    "Wurzach,,Bad-Oberschwarzach": "Bad Wurzach-Oberschwarzach",
    "Wustrow,,Ostseebad": "Wustrow Ostseebad",
    "Wörishofen,,Bad": "Bad Wörishofen",
    "Wörth,am,Main": "Wörth am Main",
    "Wörth/Oberbayern,-Hörlkofen": "Wörth/Oberbayern-Hörlkofen",
    "Wörth/Oberpfalz,-Kiefenholz": "Wörth/Oberpfalz-Kiefenholz",
    "Zell,,Kreis,Hof": "Zell Kreis Hof",
    "Zell,am,Harmersbach": "Zell am Harmersbach",
    "Zell,im,Wiesental,-Pfaffenberg": "Zell im Wiesental-Pfaffenberg",
    "Zingst,,Ostseeheilbad": "Zingst Ostseeheilbad",
    "Zwesten,,Bad": "Bad Zwesten",
    "Zwischenahn,,Bad": "Bad Zwischenahn",
    "Zwischenahn,,Bad-Westerholtsfelde": "Bad Zwischenahn-Westerholtsfelde",
}

## Functions

In [7]:
def prepare_outdir(out_path, verbose=False):
    """create (nested) output folders

    Args:
        out_path (string): directory (e.g. 'data', 'data/more_data/', '../data/')
        verbose (bool, optional): print more information. Defaults to False.
    """
    # get current path (to return to)
    path = os.getcwd()
    if verbose:
        print("Current path:", path)

    # iterate over all directories (if nested)
    my_path = out_path.split("/")
    if verbose:
        print("Output directory",my_path)
    curr_dir = "."
    while len(my_path) > 0:
        # change if last subdirectory is created
        if len(my_path) == 0 or my_path == [""]:
            break

        # track current (sub)directory
        curr_dir = curr_dir + "/" + my_path[0]
        if not my_path[0] in ("", ".") :
            # create subdirectory, if require
            if not os.path.isdir(my_path[0]):
                print("Created directory", curr_dir)
                os.mkdir(my_path[0])
            # change working directory to new subdirectory
            os.chdir(my_path[0])
        
        # remove current subdirectory from list
        if len(my_path) > 1:
            my_path = my_path[1:]
        else:
            break # my_path = []
    
    # go back to original working directory
    os.chdir(path)

In [8]:
# https://stackoverflow.com/questions/11023530/python-to-list-http-files-and-directories
def get_file_list_from_html(url, ext=''):
    """get available files from current url

    Args:
        url (str): web link
        ext (str, optional): file extension. Defaults to ''.

    Returns:
        list: files (with required extension)
    """
    # ensure correct url format
    if url.endswith("/"):
        url = url[:-1]
    
    # request web page and parse it
    page = requests.get(url).text
    soup = BeautifulSoup(page, 'html.parser')

    # create file list
    file_list = [url + '/' + node.get('href') for node in soup.find_all('a') if node.get('href').endswith(ext)]
    return file_list

In [9]:
def get_weather_station_IDs(out_path, filename, web_tag, data_tag, verbose=False):
    """identify relevant weather stations (data since at least 2005 up to today)

    Args:
        out_path (str): path to save filtered information on weather stations
        filename (str): description of the data (e.g. ST_Stundenwerte_Beschreibung_Stationen.txt)
        web_tag (str): tag used on website (e.g. ST)
        data_tag (str): tag used locally (e.g. sun_hourly)

    Returns:
        list: IDs of relevant weather stations
    """

    if filename == "":
        print("\nNo filename provided!")
        return []

    print("\nIdentifying available data from %s" % filename)
    # Note: use bytestring for special German characters
    # otherwise error: "utf-8' codec can't decode byte 0xfc in position 144: invalid start byte"
    
    # collect weather stations with current data only
    outfile_name = data_tag + '_current_dwd_stations_%s_%s_data.csv' % (web_tag, data_tag)
    outfile = open(out_path+outfile_name, 'wb')
    
    # collect relevant information on time, place and ID
    list_start_dates = []
    list_cities = []
    list_ids = []
    count = 0
    if not out_path.startswith("../"):
        path_name = "./"+out_path
    else:
        path_name = out_path
    with open(path_name+filename, 'rb') as infile:
        for line in infile:
            if verbose:
                # encode string with umlauts (special German characters)
                if "litz" in line.decode('windows-1252'):
                    print("byte string:", line.strip())
                    print("converted:    ", line.decode('windows-1252'))
            
            # replace spaces by commas for output csv and decode string
            text = re.sub(' +', ',', line.strip().decode('windows-1252'))
            # correct for city names containing spaces
            text = text.replace(",(", " (")
            for key, val in location_dict.items():
                if key in text:
                    text = text.replace(key, val)
            # check for other city names containing spaces
            if len(text.split(",")) > 8:
                print(text)

            # get optional information on city and time window
            if verbose:
                info = text.split(",")[1:3]
                info.extend(text.split(",")[6:8])
            
            # keep header
            elif not text[0].isdigit() and text[:5]!="-----":
                outfile.write((text+"\n").encode('utf-8'))
            # ensure recent data
            if "20230" in text:
                start_date = text.split(",")[1]
                # ensure long data range
                if start_date[:4] <= "2005":
                    count += 1
                    list_ids.append(text.split(",")[0])
                    list_start_dates.append(start_date)
                    list_cities.append(text.split(",")[6])
                    outfile.write((text+"\n").encode('utf-8'))
                else:
                    if verbose:
                        print("too young:  ", "\t".join(info))
            elif text[:5]!="-----":
                if verbose:
                    print("not current:", "\t".join(info))

    # summarize findings
    print("\n%d German weather stations with current hourly sun data remaining." % count)
    if count > 0:
        print("  Recording started between %s and %s" % (min(list_start_dates), max(list_start_dates)))
        print("  Cities:", ", ".join(sorted(list_cities)))
        print("  IDs", ", ".join(list_ids))
    outfile.close()
    return list_ids

In [10]:
def download_and_unpack_weather_data(out_path, base_url, web_tag, data_tag, list_ids, 
                                     verbose=False, overwrite=True, archive=True):
    """collect relevant weather stations (data since at least 2005 up to today)

    Args:
        out_path (str): path to save filtered information on weather stations
        base_url (str): url with *.zip data
        web_tag (str): tag used on website (e.g. ST)
        data_tag (str): tag used locally (e.g. sun_hourly)
        list_ids (list): pre-selectedrelevant IDs
        overwrite (bool, optional): overwrite/update old data
        verbose (bool, optional): verbosity. Defaults to False.
    """

    # get current path
    data_path = os.path.abspath('')
    print("\nStarting download of %d files from url" % (len(list_ids)), base_url)
    
    # check, if directory is present or create it
    out_dir = out_path + data_tag
    prepare_outdir(out_path=out_dir)

    # check already present data files to not download them again
    txt_files = glob.glob(data_path+"/"+out_path+data_tag+"/*.txt")
    txt_ids = []
    for name in txt_files:
        if "produkt" in name.lower() and name.endswith(".txt"):
            txt_ids.append(name.split("_")[-1].split(".")[0])
        elif not name.endswith(".txt"):
            txt_files.remove(name)

    # check if some files are already present
    if len(txt_ids) != 0:
        print("%d data files already present: %s\n" % (len(txt_ids), ", ".join(txt_ids)))

    # check if no download is required
    if len(txt_ids) == len(list_ids) and not overwrite:
        if set(txt_ids) == set(list_ids):
            print("No download required and no update made!\n")
            if verbose:
                print("Lengths of available data files:")
                !wc -l */*/*/*prod*
                return

    # download all zip files
    # track number of downloads
    id_track = [[],[]] # downloaded, present
    url_list = get_file_list_from_html(base_url, ext='')
    for id in sorted(list_ids):
        filename = None
        if verbose:
            print("\n".join(url_list))
        for url in url_list:
            if id in url:
                filename = url.split("/")[-1]
                break
        if filename == None:
            print("Note: No file available for id", id)
            continue
        # skip existing data files (zip file present or unpacked data file)
        if overwrite or (not os.path.exists(out_dir+"/"+filename) and not id in txt_ids):
            webpage = requests.get(url, allow_redirects=True)
            open(out_dir+"/"+filename, 'wb').write(webpage.content)
            id_track[0].append(id)
            # # alternative download approaches
            # subprocess.run(['wget', url], stdout=False) # not completing the file download!
            # subprocess.run(['curl', '-O'] + [url], stdout=False) # not completing the file download!
        else:
            id_track[1].append(id)
    if len(id_track[0])!=0:
        print("%d files downloaded from %s: \n\t%s\n" % (len(id_track[0]), base_url, ", ".join(id_track[0])))
    # if len(id_track[1])!=0:
    #     print("%d files were already loaded: %s\n" % (len(id_track[1]), ", ".join(id_track[1])))

    # switch to data directory to unpack the data
    if not os.getcwd().replace("/", "").replace("\\", "").endswith(out_dir.replace("/", "").replace("\\", "")):
        os.chdir(out_dir)

    # unpack all zip files in another subdirectory and clean up later
    files_long = glob.glob(os.path.abspath('')+"/*.zip")
    if files_long != []:
        print("%d zip data files to unpack" % (len(files_long)))
        subprocess.call(['unzip', "-o", "-q", '*.zip'], stdout=True)

        # delete unnecessary files
        files_long = glob.glob(os.path.abspath('')+"/*.html")
        print("  %d html files deleted." % (len(files_long)))
        subprocess.call(['rm','-r'] + files_long)
        files_long = glob.glob(os.path.abspath('')+"*/Metadaten*.txt")
        print("  %d metadata files deleted." % (len(files_long)))
        subprocess.call(['rm','-r'] + files_long)

        # delete zip files
        if not archive:
            files_long = glob.glob(os.path.abspath('')+"/*.zip")
            print("Deleting %d zip files" % (len(files_long)))
            subprocess.call(['rm','-r'] + files_long)
        # or move zip files to archive
        else:
            files_long = glob.glob(os.path.abspath('')+"/*.zip")
            files_long_moved = [x[:x.rfind("/")] + "/archive" for x in files_long]
            if not os.path.isdir('archive'):
                os.mkdir('archive')
            print("  %d zip files archived.\n" % len(files_long))
            subprocess.Popen(['mv'] + files_long + files_long_moved, stdout=False, stderr=False)

    if verbose:
        # get information on available data
        print("\nLengths of available data files:")
        !wc -l *prod*

    # switch back to original path
    os.chdir(data_path)

## Collect hourly weather data

### Solar Data

Solar data availability:
- hourly data from [dwd](https://opendata.dwd.de/climate_environment/CDC/observations_germany/climate/hourly/solar/ST_Stundenwerte_Beschreibung_Stationen.txt)

Download this data first, as it is of highest relevance. Thus, this data should be recorded over a long period of time up to today. Consequently, this idea list can be used to filter the number of weather stations of interest.

In [11]:
# go to working directory
os.chdir(path)

# relevant information and variables for solar data
url = "https://opendata.dwd.de/climate_environment/CDC/observations_germany/climate/hourly/solar/"
web_tag  = "ST"
data_tag = "ST_solar_hourly"

# create required directories
prepare_outdir(out_path)

# save descriptive PDF 
description_pdfs = get_file_list_from_html(url, "pdf")
for link in description_pdfs:
    filenames = (data_tag + "_" + link.split("/")[-1]).replace("__", "_")
    webpage = requests.get(link, allow_redirects=True)
    print(path+"/"+out_path)
    open(path+"/"+out_path+filenames, 'wb').write(webpage.content)

# get descriptive text file and screen it
txt_urls = get_file_list_from_html(url, descriptive_suffix)
if len(txt_urls) == 1:
    description_url = txt_urls[0]
else:
    print("Multiple txt files on", url, "\n  ->", 
          [x.split("/")[-1] for x in txt_urls])

# download description file 
filename = description_url.split("/")[-1]
webpage = requests.get(description_url, allow_redirects=True)
open(path+"/"+out_path+filename, 'wb').write(webpage.content)

# identify available, informative weather stations from description file
list_ids = get_weather_station_IDs(out_path, filename, web_tag, data_tag)
base_ids = list_ids[:]

Created directory ./../data/weather/weather-hourly
/Users/kathse/Documents/NeueFische/4_Capstone/capstone_solar_energy/notebooks/../data/weather/weather-hourly/
/Users/kathse/Documents/NeueFische/4_Capstone/capstone_solar_energy/notebooks/../data/weather/weather-hourly/



Identifying available data from ST_Stundenwerte_Beschreibung_Stationen.txt

23 German weather stations with current hourly sun data remaining.
  Recording started between 19451231 and 20050101
  Cities: Arkona, Braunschweig, Chemnitz, Dresden-Klotzsche, Fichtelberg, Fürstenzell, Görlitz, Hamburg-Fuhlsbüttel, Hohenpeißenberg, Konstanz, Lindenberg, Mannheim, Norderney, Potsdam, Rostock-Warnemünde, Saarbrücken-Ensheim, Schleswig, Seehausen, Stuttgart (Schnarrenberg), Trier-Petrisberg, Weihenstephan-Dürnast, Würzburg, Zinnwald-Georgenfeld
  IDs 00183, 00662, 00853, 01048, 01358, 01684, 01975, 02290, 02712, 03015, 03631, 03987, 04271, 04336, 04466, 04642, 04928, 05100, 05404, 05705, 05779, 05856, 05906


In [12]:
# download & unpack solar data
download_and_unpack_weather_data(out_path, url, web_tag, data_tag, list_ids, overwrite=False)


Starting download of 23 files from url https://opendata.dwd.de/climate_environment/CDC/observations_germany/climate/hourly/solar/
Created directory ./../data/weather/weather-hourly/ST_solar_hourly
23 files downloaded from https://opendata.dwd.de/climate_environment/CDC/observations_germany/climate/hourly/solar/: 
	00183, 00662, 00853, 01048, 01358, 01684, 01975, 02290, 02712, 03015, 03631, 03987, 04271, 04336, 04466, 04642, 04928, 05100, 05404, 05705, 05779, 05856, 05906

23 zip data files to unpack
  131 html files deleted.
  154 metadata files deleted.
  23 zip files archived.




23 archives were successfully processed.


### Remaining data

Available hourly data: 
             "air_temperature", "cloud_type", "cloudiness", "dew_point", "extreme_wind", 
             "moisture", "precipitation", "pressure", "soil_temperature", "solar", "sun", 
             "visibility", "weather_phenomena", "wind", "wind_synop"

In [13]:
def main(url, web_tag, data_tag, base_ids):
    # print current task
    print("="*80, "\n" + data_tag + "\n")

    # create output folders
    os.chdir(path)
    prepare_outdir(out_path)

    # save descriptive PDF 
    description_pdfs = get_file_list_from_html(url, "pdf")
    if len(description_pdfs) == 0:
        description_pdfs = get_file_list_from_html(url[:url[:-1].rfind("/")], "pdf")
        print("searching descriptive PDFs...", description_pdfs)
    for link in description_pdfs:
        pdf_name = (data_tag + "_" + link.split("/")[-1]).replace("__", "_")
        webpage = requests.get(link, allow_redirects=True)
        open(path+"/"+out_path+pdf_name, 'wb').write(webpage.content)

    # get descriptive text file and screen it
    txt_urls = get_file_list_from_html(url, descriptive_suffix)
    if len(txt_urls) > 1:
        print("Multiple txt files on", url, "\n  ->", 
              [x.split("/")[-1] for x in txt_urls])

    # download description file 
    file_list = []
    for description_url in txt_urls: 
        filename = description_url.split("/")[-1]
        webpage = requests.get(description_url, allow_redirects=True)
        open(path+"/"+out_path+filename, 'wb').write(webpage.content)
        # required in case contain multiple text files
        if "beschreibung_stationen" in filename.lower():
            file_list.append(filename)

    # identify available, informative weather stations from description file
    list_ids = []
    for filename in file_list:
        list_ids.extend(get_weather_station_IDs(out_path, filename, web_tag, data_tag))

    if len(list_ids) > 5:
        base_ids = set(list_ids).intersection(base_ids)
    
    print("\nFocussing on %d cities with complete data." % len(base_ids))

    # download & unpack more sun data
    download_and_unpack_weather_data(out_path, url, web_tag, data_tag, base_ids, overwrite=False)

In [14]:
for idx in range(len(list_web_tags)):
    url = list_urls[idx]
    web_tag = list_web_tags[idx]
    data_tag = list_data_tags[idx]

    main(url, web_tag, data_tag, base_ids)

SD_sun_hourly_recent



searching descriptive PDFs... ['https://opendata.dwd.de/climate_environment/CDC/observations_germany/climate/hourly/sun/BESCHREIBUNG_obsgermany_climate_hourly_sun_de.pdf', 'https://opendata.dwd.de/climate_environment/CDC/observations_germany/climate/hourly/sun/DESCRIPTION_obsgermany_climate_hourly_sun_en.pdf']

Identifying available data from SD_Stundenwerte_Beschreibung_Stationen.txt

202 German weather stations with current hourly sun data remaining.
  Recording started between 18900101 and 20051201
  Cities: Aldersbach-Kriestorf, Altheim Kreis Biberach, Alzey, Amerang-Pfaffing, Angermünde, Arkona, Augsburg, Bad Bergzabern, Bad Hersfeld, Bad Kissingen, Bad Kreuznach, Bad Lauchstädt, Bad Lippspringe, Bad Marienberg, Bamberg, Barth, Bassum, Berge, Berlin Brandenburg, Berlin-Dahlem (FU), Bertsdorf-Hörnitz, Berus, Boizenburg, Boltenhagen, Braunschweig, Bremen, Bremerhaven, Bremervörde, Brocken, Carlsfeld, Chemnitz, Chieming, Cottbus, Cuxhaven, Deuselbach, Diepholz, Dillenburg, Doberlug-K


23 archives were successfully processed.


searching descriptive PDFs... ['https://opendata.dwd.de/climate_environment/CDC/observations_germany/climate/hourly/sun/BESCHREIBUNG_obsgermany_climate_hourly_sun_de.pdf', 'https://opendata.dwd.de/climate_environment/CDC/observations_germany/climate/hourly/sun/DESCRIPTION_obsgermany_climate_hourly_sun_en.pdf']

Identifying available data from SD_Stundenwerte_Beschreibung_Stationen.txt

202 German weather stations with current hourly sun data remaining.
  Recording started between 18900101 and 20051201
  Cities: Aldersbach-Kriestorf, Altheim Kreis Biberach, Alzey, Amerang-Pfaffing, Angermünde, Arkona, Augsburg, Bad Bergzabern, Bad Hersfeld, Bad Kissingen, Bad Kreuznach, Bad Lauchstädt, Bad Lippspringe, Bad Marienberg, Bamberg, Barth, Bassum, Berge, Berlin Brandenburg, Berlin-Dahlem (FU), Bertsdorf-Hörnitz, Berus, Boizenburg, Boltenhagen, Braunschweig, Bremen, Bremerhaven, Bremervörde, Brocken, Carlsfeld, Chemnitz, Chieming, Cottbus, Cuxhaven, Deuselbach, Diepholz, Dillenburg, Doberlug-K


23 archives were successfully processed.


  92 html files deleted.
  138 metadata files deleted.
  23 zip files archived.

N_cloudiness_recent

searching descriptive PDFs... ['https://opendata.dwd.de/climate_environment/CDC/observations_germany/climate/hourly/cloudiness/BESCHREIBUNG_obsgermany_climate_hourly_cloudiness_de.pdf', 'https://opendata.dwd.de/climate_environment/CDC/observations_germany/climate/hourly/cloudiness/DESCRIPTION_obsgermany_climate_hourly_cloudiness_en.pdf']

Identifying available data from N_Stundenwerte_Beschreibung_Stationen.txt

169 German weather stations with current hourly sun data remaining.
  Recording started between 19490101 and 20050718
  Cities: Altenstadt, Angermünde, Arkona, Artern, Augsburg, Bad Hersfeld, Bad Kissingen, Bad Lippspringe, Bad Marienberg, Bad Salzuflen, Bamberg, Barth, Baruth, Bergen, Berlin-Dahlem (FU), Berlin-Tempelhof, Berus, Boizenburg, Boltenhagen, Braunlage, Braunschweig, Bremen, Bremerhaven, Bremervörde, Brocken, Büchel (Flugplatz), Bückeburg, Carlsfeld, Celle, Chemnitz


22 archives were successfully processed.


searching descriptive PDFs... ['https://opendata.dwd.de/climate_environment/CDC/observations_germany/climate/hourly/cloudiness/BESCHREIBUNG_obsgermany_climate_hourly_cloudiness_de.pdf', 'https://opendata.dwd.de/climate_environment/CDC/observations_germany/climate/hourly/cloudiness/DESCRIPTION_obsgermany_climate_hourly_cloudiness_en.pdf']

Identifying available data from N_Stundenwerte_Beschreibung_Stationen.txt

169 German weather stations with current hourly sun data remaining.
  Recording started between 19490101 and 20050718
  Cities: Altenstadt, Angermünde, Arkona, Artern, Augsburg, Bad Hersfeld, Bad Kissingen, Bad Lippspringe, Bad Marienberg, Bad Salzuflen, Bamberg, Barth, Baruth, Bergen, Berlin-Dahlem (FU), Berlin-Tempelhof, Berus, Boizenburg, Boltenhagen, Braunlage, Braunschweig, Bremen, Bremerhaven, Bremervörde, Brocken, Büchel (Flugplatz), Bückeburg, Carlsfeld, Celle, Chemnitz, Chieming, Cottbus, Cuxhaven, Deuselbach, Diepholz, Doberlug-Kirchhain, Dresden-Klotzsche, Düsseldorf


22 archives were successfully processed.


  88 html files deleted.
  132 metadata files deleted.
  22 zip files archived.

CS_cloud_type_recent

searching descriptive PDFs... ['https://opendata.dwd.de/climate_environment/CDC/observations_germany/climate/hourly/cloud_type/BESCHREIBUNG_obsgermany_climate_hourly_cloud_type_de.pdf', 'https://opendata.dwd.de/climate_environment/CDC/observations_germany/climate/hourly/cloud_type/DESCRIPTION_obsgermany_climate_hourly_cloud_type_en.pdf']

Identifying available data from CS_Stundenwerte_Beschreibung_Stationen.txt

798 German weather stations with current hourly sun data remaining.
  Recording started between 19490101 and 20051201
  Cities: Abtsgmünd-Untergröningen, Achenkirch/Österreich, Ahrensfelde, Alfhausen, Alperstedt, Alsfeld-Eifa, Altendorf, Altendorf/Oberfranken, Altenstadt, Altertheim-Oberaltertheim, Altheim Kreis Biberach, Altomünster-Maisbrunn, Altshausen, Alzey, Amberg-Unterammersricht, Amerang-Pfaffing, Amorbach-Neudorf, Ampfing (Kläranlage), Amöneburg-Rüdigheim, Angermünde


22 archives were successfully processed.


  176 html files deleted.
  220 metadata files deleted.
  22 zip files archived.

CS_cloud_type_historical

searching descriptive PDFs... ['https://opendata.dwd.de/climate_environment/CDC/observations_germany/climate/hourly/cloud_type/BESCHREIBUNG_obsgermany_climate_hourly_cloud_type_de.pdf', 'https://opendata.dwd.de/climate_environment/CDC/observations_germany/climate/hourly/cloud_type/DESCRIPTION_obsgermany_climate_hourly_cloud_type_en.pdf']

Identifying available data from CS_Stundenwerte_Beschreibung_Stationen.txt

798 German weather stations with current hourly sun data remaining.
  Recording started between 19490101 and 20051201
  Cities: Abtsgmünd-Untergröningen, Achenkirch/Österreich, Ahrensfelde, Alfhausen, Alperstedt, Alsfeld-Eifa, Altendorf, Altendorf/Oberfranken, Altenstadt, Altertheim-Oberaltertheim, Altheim Kreis Biberach, Altomünster-Maisbrunn, Altshausen, Alzey, Amberg-Unterammersricht, Amerang-Pfaffing, Amorbach-Neudorf, Ampfing (Kläranlage), Amöneburg-Rüdigheim, Anger


22 archives were successfully processed.


  176 html files deleted.
  220 metadata files deleted.
  22 zip files archived.

VV_visibility_recent

searching descriptive PDFs... ['https://opendata.dwd.de/climate_environment/CDC/observations_germany/climate/hourly/visibility/BESCHREIBUNG_obsgermany_climate_hourly_visibility_de.pdf', 'https://opendata.dwd.de/climate_environment/CDC/observations_germany/climate/hourly/visibility/DESCRIPTION_obsgermany_climate_hourly_visibility_en.pdf']

Identifying available data from VV_Stundenwerte_Beschreibung_Stationen.txt

175 German weather stations with current hourly sun data remaining.
  Recording started between 19490101 and 20050908
  Cities: Altenstadt, Angermünde, Arkona, Artern, Augsburg, Bad Hersfeld, Bad Kissingen, Bad Lippspringe, Bad Marienberg, Bad Salzuflen, Bamberg, Barth, Baruth, Bergen, Berlin-Dahlem (FU), Berlin-Tempelhof, Berus, Boizenburg, Boltenhagen, Braunlage, Braunschweig, Bremen, Bremerhaven, Bremervörde, Brocken, Büchel (Flugplatz), Bückeburg, Carlsfeld, Celle, Chemn


22 archives were successfully processed.


searching descriptive PDFs... ['https://opendata.dwd.de/climate_environment/CDC/observations_germany/climate/hourly/visibility/BESCHREIBUNG_obsgermany_climate_hourly_visibility_de.pdf', 'https://opendata.dwd.de/climate_environment/CDC/observations_germany/climate/hourly/visibility/DESCRIPTION_obsgermany_climate_hourly_visibility_en.pdf']

Identifying available data from VV_Stundenwerte_Beschreibung_Stationen.txt

175 German weather stations with current hourly sun data remaining.
  Recording started between 19490101 and 20050908
  Cities: Altenstadt, Angermünde, Arkona, Artern, Augsburg, Bad Hersfeld, Bad Kissingen, Bad Lippspringe, Bad Marienberg, Bad Salzuflen, Bamberg, Barth, Baruth, Bergen, Berlin-Dahlem (FU), Berlin-Tempelhof, Berus, Boizenburg, Boltenhagen, Braunlage, Braunschweig, Bremen, Bremerhaven, Bremervörde, Brocken, Büchel (Flugplatz), Bückeburg, Carlsfeld, Celle, Chemnitz, Chieming, Cottbus, Cuxhaven, Deuselbach, Diepholz, Doberlug-Kirchhain, Dresden-Klotzsche, Dörnick, 


22 archives were successfully processed.


  88 html files deleted.
  132 metadata files deleted.
  22 zip files archived.

FX_extreme_wind_recent

searching descriptive PDFs... ['https://opendata.dwd.de/climate_environment/CDC/observations_germany/climate/hourly/extreme_wind/BESCHREIBUNG_obsgermany_climate_hourly_extreme_wind_de.pdf', 'https://opendata.dwd.de/climate_environment/CDC/observations_germany/climate/hourly/extreme_wind/DESCRIPTION_obsgermany_climate_hourly_extreme_wind_en.pdf']

Identifying available data from FX_Stundenwerte_Beschreibung_Stationen.txt

186 German weather stations with current hourly sun data remaining.
  Recording started between 19700402 and 20051020
  Cities: Altenstadt, Angermünde, Arkona, Artern, Augsburg, Bad Hersfeld, Bad Kissingen, Bad Lippspringe, Bad Marienberg, Bad Salzuflen, Bamberg, Barth, Baruth, Bergen, Berlin Brandenburg, Berlin-Dahlem (FU), Berlin-Tempelhof, Bertsdorf-Hörnitz, Berus, Boizenburg, Boltenhagen, Braunlage, Braunschweig, Bremen, Bremerhaven, Bremervörde, Brocken, Büchel


22 archives were successfully processed.


searching descriptive PDFs... ['https://opendata.dwd.de/climate_environment/CDC/observations_germany/climate/hourly/extreme_wind/BESCHREIBUNG_obsgermany_climate_hourly_extreme_wind_de.pdf', 'https://opendata.dwd.de/climate_environment/CDC/observations_germany/climate/hourly/extreme_wind/DESCRIPTION_obsgermany_climate_hourly_extreme_wind_en.pdf']

Identifying available data from FX_Stundenwerte_Beschreibung_Stationen.txt

186 German weather stations with current hourly sun data remaining.
  Recording started between 19700402 and 20051020
  Cities: Altenstadt, Angermünde, Arkona, Artern, Augsburg, Bad Hersfeld, Bad Kissingen, Bad Lippspringe, Bad Marienberg, Bad Salzuflen, Bamberg, Barth, Baruth, Bergen, Berlin Brandenburg, Berlin-Dahlem (FU), Berlin-Tempelhof, Bertsdorf-Hörnitz, Berus, Boizenburg, Boltenhagen, Braunlage, Braunschweig, Bremen, Bremerhaven, Bremervörde, Brocken, Büchel (Flugplatz), Bückeburg, Carlsfeld, Celle, Chemnitz, Chieming, Cottbus, Cuxhaven, Deuselbach, Diepholz, D


22 archives were successfully processed.


  88 html files deleted.
  132 metadata files deleted.
  22 zip files archived.

FF_wind_recent

searching descriptive PDFs... ['https://opendata.dwd.de/climate_environment/CDC/observations_germany/climate/hourly/wind/BESCHREIBUNG_obsgermany_climate_hourly_wind_de.pdf', 'https://opendata.dwd.de/climate_environment/CDC/observations_germany/climate/hourly/wind/DESCRIPTION_obsgermany_climate_hourly_wind_en.pdf']

Identifying available data from FF_Stundenwerte_Beschreibung_Stationen.txt

219 German weather stations with current hourly sun data remaining.
  Recording started between 18930101 and 20050908
  Cities: Alsfeld, Altenstadt, Altmühlsee, Andernach, Angermünde, Arkona, Artern, Augsburg, Bad Arolsen-Volkhardinghausen, Bad Hersfeld, Bad Kissingen, Bad Lippspringe, Bad Marienberg, Bad Salzuflen, Bad Waldsee-Reute, Bamberg, Barth, Baruth, Bastorf-Kägsdorf (SWN), Bergen, Berlin Brandenburg, Berlin-Tempelhof, Bertsdorf-Hörnitz, Berus, Boizenburg, Boltenhagen, Borkum-Süderstraße, Brake, B


23 archives were successfully processed.


searching descriptive PDFs... ['https://opendata.dwd.de/climate_environment/CDC/observations_germany/climate/hourly/wind/BESCHREIBUNG_obsgermany_climate_hourly_wind_de.pdf', 'https://opendata.dwd.de/climate_environment/CDC/observations_germany/climate/hourly/wind/DESCRIPTION_obsgermany_climate_hourly_wind_en.pdf']

Identifying available data from FF_Stundenwerte_Beschreibung_Stationen.txt

219 German weather stations with current hourly sun data remaining.
  Recording started between 18930101 and 20050908
  Cities: Alsfeld, Altenstadt, Altmühlsee, Andernach, Angermünde, Arkona, Artern, Augsburg, Bad Arolsen-Volkhardinghausen, Bad Hersfeld, Bad Kissingen, Bad Lippspringe, Bad Marienberg, Bad Salzuflen, Bad Waldsee-Reute, Bamberg, Barth, Baruth, Bastorf-Kägsdorf (SWN), Bergen, Berlin Brandenburg, Berlin-Tempelhof, Bertsdorf-Hörnitz, Berus, Boizenburg, Boltenhagen, Borkum-Süderstraße, Brake, Brandenburg/Havel, Braunlage, Braunschweig, Bremen, Bremerhaven, Bremervörde, Brocken, Büchel (Flu


23 archives were successfully processed.


  115 html files deleted.
  161 metadata files deleted.
  23 zip files archived.

F_wind_synopsis_recent

searching descriptive PDFs... ['https://opendata.dwd.de/climate_environment/CDC/observations_germany/climate/hourly/wind_synop/BESCHREIBUNG_obsgermany_climate_hourly_wind_synop_de.pdf', 'https://opendata.dwd.de/climate_environment/CDC/observations_germany/climate/hourly/wind_synop/DESCRIPTION_obsgermany_climate_hourly_wind_synop_en.pdf']

Identifying available data from F_Stundenwerte_Beschreibung_Stationen.txt

203 German weather stations with current hourly sun data remaining.
  Recording started between 19490101 and 20051201
  Cities: Altenstadt, Angermünde, Arkona, Artern, Augsburg, Bad Hersfeld, Bad Kissingen, Bad Lippspringe, Bad Marienberg, Bad Salzuflen, Bamberg, Barth, Baruth, Berge, Bergen, Berlin Brandenburg, Berlin-Dahlem (FU), Berlin-Tempelhof, Bertsdorf-Hörnitz, Berus, Boizenburg, Boltenhagen, Braunlage, Braunschweig, Bremen, Bremerhaven, Bremervörde, Bremgarten (Fess


22 archives were successfully processed.


searching descriptive PDFs... ['https://opendata.dwd.de/climate_environment/CDC/observations_germany/climate/hourly/wind_synop/BESCHREIBUNG_obsgermany_climate_hourly_wind_synop_de.pdf', 'https://opendata.dwd.de/climate_environment/CDC/observations_germany/climate/hourly/wind_synop/DESCRIPTION_obsgermany_climate_hourly_wind_synop_en.pdf']

Identifying available data from F_Stundenwerte_Beschreibung_Stationen.txt

203 German weather stations with current hourly sun data remaining.
  Recording started between 19490101 and 20051201
  Cities: Altenstadt, Angermünde, Arkona, Artern, Augsburg, Bad Hersfeld, Bad Kissingen, Bad Lippspringe, Bad Marienberg, Bad Salzuflen, Bamberg, Barth, Baruth, Berge, Bergen, Berlin Brandenburg, Berlin-Dahlem (FU), Berlin-Tempelhof, Bertsdorf-Hörnitz, Berus, Boizenburg, Boltenhagen, Braunlage, Braunschweig, Bremen, Bremerhaven, Bremervörde, Bremgarten (Fessenheim), Brocken, Büchel (Flugplatz), Bückeburg, Carlsfeld, Celle, Chemnitz, Chieming, Cottbus, Cuxhaven, 


22 archives were successfully processed.


  110 html files deleted.
  154 metadata files deleted.
  22 zip files archived.

WW_weather_phenomena_recent

searching descriptive PDFs... ['https://opendata.dwd.de/climate_environment/CDC/observations_germany/climate/hourly/weather_phenomena/BESCHREIBUNG_obsgermany_climate_hourly_weather_phenomena_de.pdf', 'https://opendata.dwd.de/climate_environment/CDC/observations_germany/climate/hourly/weather_phenomena/DESCRIPTION_obsgermany_climate_hourly_weather_phenomena_en.pdf']
Multiple txt files on https://opendata.dwd.de/climate_environment/CDC/observations_germany/climate/hourly/weather_phenomena/recent/ 
  -> ['WW_Stundenwerte_Beschreibung_Stationen.txt', 'Wetter_Beschreibung.txt']

Identifying available data from WW_Stundenwerte_Beschreibung_Stationen.txt

169 German weather stations with current hourly sun data remaining.
  Recording started between 19490101 and 20050816
  Cities: Altenstadt, Angermünde, Arkona, Artern, Augsburg, Bad Hersfeld, Bad Kissingen, Bad Lippspringe, Bad Mari


22 archives were successfully processed.


searching descriptive PDFs... ['https://opendata.dwd.de/climate_environment/CDC/observations_germany/climate/hourly/weather_phenomena/BESCHREIBUNG_obsgermany_climate_hourly_weather_phenomena_de.pdf', 'https://opendata.dwd.de/climate_environment/CDC/observations_germany/climate/hourly/weather_phenomena/DESCRIPTION_obsgermany_climate_hourly_weather_phenomena_en.pdf']
Multiple txt files on https://opendata.dwd.de/climate_environment/CDC/observations_germany/climate/hourly/weather_phenomena/historical/ 
  -> ['WW_Stundenwerte_Beschreibung_Stationen.txt', 'Wetter_Beschreibung.txt']

Identifying available data from WW_Stundenwerte_Beschreibung_Stationen.txt

169 German weather stations with current hourly sun data remaining.
  Recording started between 19490101 and 20050816
  Cities: Altenstadt, Angermünde, Arkona, Artern, Augsburg, Bad Hersfeld, Bad Kissingen, Bad Lippspringe, Bad Marienberg, Bad Salzuflen, Bamberg, Barth, Bergen, Berlin-Dahlem (FU), Berlin-Tempelhof, Berus, Boizenburg, Bol


22 archives were successfully processed.


  66 html files deleted.
  110 metadata files deleted.
  22 zip files archived.

RR_precipitation_recent

searching descriptive PDFs... ['https://opendata.dwd.de/climate_environment/CDC/observations_germany/climate/hourly/precipitation/BESCHREIBUNG_obsgermany_climate_hourly_precipitation_de.pdf', 'https://opendata.dwd.de/climate_environment/CDC/observations_germany/climate/hourly/precipitation/DESCRIPTION_obsgermany_climate_hourly_precipitation_en.pdf']

Identifying available data from RR_Stundenwerte_Beschreibung_Stationen.txt

754 German weather stations with current hourly sun data remaining.
  Recording started between 19950901 and 20051201
  Cities: Abtsgmünd-Untergröningen, Achenkirch/Österreich, Ahrensfelde, Alfhausen, Alperstedt, Alsfeld-Eifa, Altendorf, Altendorf/Oberfranken, Altertheim-Oberaltertheim, Altheim Kreis Biberach, Altomünster-Maisbrunn, Altshausen, Alzey, Amberg-Unterammersricht, Amerang-Pfaffing, Amorbach-Neudorf, Ampfing (Kläranlage), Amöneburg-Rüdigheim, Angermü


22 archives were successfully processed.


searching descriptive PDFs... ['https://opendata.dwd.de/climate_environment/CDC/observations_germany/climate/hourly/precipitation/BESCHREIBUNG_obsgermany_climate_hourly_precipitation_de.pdf', 'https://opendata.dwd.de/climate_environment/CDC/observations_germany/climate/hourly/precipitation/DESCRIPTION_obsgermany_climate_hourly_precipitation_en.pdf']

Identifying available data from RR_Stundenwerte_Beschreibung_Stationen.txt

754 German weather stations with current hourly sun data remaining.
  Recording started between 19950901 and 20051201
  Cities: Abtsgmünd-Untergröningen, Achenkirch/Österreich, Ahrensfelde, Alfhausen, Alperstedt, Alsfeld-Eifa, Altendorf, Altendorf/Oberfranken, Altertheim-Oberaltertheim, Altheim Kreis Biberach, Altomünster-Maisbrunn, Altshausen, Alzey, Amberg-Unterammersricht, Amerang-Pfaffing, Amorbach-Neudorf, Ampfing (Kläranlage), Amöneburg-Rüdigheim, Angermünde, Anklam, Arkona, Arnsberg-Neheim, Arnstein-Müdesheim, Artern, Aschau-Stein, Attendorn-Neulisternohl, A


22 archives were successfully processed.


  130 html files deleted.
  174 metadata files deleted.
  22 zip files archived.

TD_dewpoint_recent

searching descriptive PDFs... ['https://opendata.dwd.de/climate_environment/CDC/observations_germany/climate/hourly/dew_point/BESCHREIBUNG_obsgermany_climate_hourly_dew_point_de.pdf', 'https://opendata.dwd.de/climate_environment/CDC/observations_germany/climate/hourly/dew_point/DESCRIPTION_obsgermany_climate_hourly_dew_point_en.pdf']

Identifying available data from TD_Stundenwerte_Beschreibung_Stationen.txt

382 German weather stations with current hourly sun data remaining.
  Recording started between 19490101 and 20051201
  Cities: Alfhausen, Alsfeld-Eifa, Altenstadt, Altheim Kreis Biberach, Altomünster-Maisbrunn, Alzey, Amberg-Unterammersricht, Amerang-Pfaffing, Angermünde, Anklam, Arkona, Arnsberg-Neheim, Arnstein-Müdesheim, Artern, Attenkam, Aue, Augsburg, Bad Bergzabern, Bad Berleburg-Stünzel, Bad Dürkheim, Bad Hersfeld, Bad Kissingen, Bad Kreuznach, Bad Königshofen, Bad Lippspr


22 archives were successfully processed.


searching descriptive PDFs... ['https://opendata.dwd.de/climate_environment/CDC/observations_germany/climate/hourly/dew_point/BESCHREIBUNG_obsgermany_climate_hourly_dew_point_de.pdf', 'https://opendata.dwd.de/climate_environment/CDC/observations_germany/climate/hourly/dew_point/DESCRIPTION_obsgermany_climate_hourly_dew_point_en.pdf']

Identifying available data from TD_Stundenwerte_Beschreibung_Stationen.txt

382 German weather stations with current hourly sun data remaining.
  Recording started between 19490101 and 20051201
  Cities: Alfhausen, Alsfeld-Eifa, Altenstadt, Altheim Kreis Biberach, Altomünster-Maisbrunn, Alzey, Amberg-Unterammersricht, Amerang-Pfaffing, Angermünde, Anklam, Arkona, Arnsberg-Neheim, Arnstein-Müdesheim, Artern, Attenkam, Aue, Augsburg, Bad Bergzabern, Bad Berleburg-Stünzel, Bad Dürkheim, Bad Hersfeld, Bad Kissingen, Bad Kreuznach, Bad Königshofen, Bad Lippspringe, Bad Marienberg, Bad Muskau, Bad Nauheim, Bad Neuenahr-Ahrweiler, Bad Salzuflen, Bad Salzungen-Gr


22 archives were successfully processed.


  66 html files deleted.
  110 metadata files deleted.
  22 zip files archived.

TF_moisture_recent

searching descriptive PDFs... ['https://opendata.dwd.de/climate_environment/CDC/observations_germany/climate/hourly/moisture/BESCHREIBUNG_obsgermany_climate_hourly_moisture_de.pdf', 'https://opendata.dwd.de/climate_environment/CDC/observations_germany/climate/hourly/moisture/DESCRIPTION_obsgermany_climate_hourly_moisture_en.pdf']

Identifying available data from TF_Stundenwerte_Beschreibung_Stationen.txt

388 German weather stations with current hourly sun data remaining.
  Recording started between 19490101 and 20051201
  Cities: Alfhausen, Alsfeld-Eifa, Altenstadt, Altheim Kreis Biberach, Altomünster-Maisbrunn, Alzey, Amberg-Unterammersricht, Amerang-Pfaffing, Angermünde, Anklam, Arkona, Arnsberg-Neheim, Arnstein-Müdesheim, Artern, Attenkam, Aue, Augsburg, Bad Bergzabern, Bad Berleburg-Stünzel, Bad Dürkheim, Bad Hersfeld, Bad Kissingen, Bad Kreuznach, Bad Königshofen, Bad Lippspringe,


22 archives were successfully processed.


searching descriptive PDFs... ['https://opendata.dwd.de/climate_environment/CDC/observations_germany/climate/hourly/moisture/BESCHREIBUNG_obsgermany_climate_hourly_moisture_de.pdf', 'https://opendata.dwd.de/climate_environment/CDC/observations_germany/climate/hourly/moisture/DESCRIPTION_obsgermany_climate_hourly_moisture_en.pdf']

Identifying available data from TF_Stundenwerte_Beschreibung_Stationen.txt

388 German weather stations with current hourly sun data remaining.
  Recording started between 19490101 and 20051201
  Cities: Alfhausen, Alsfeld-Eifa, Altenstadt, Altheim Kreis Biberach, Altomünster-Maisbrunn, Alzey, Amberg-Unterammersricht, Amerang-Pfaffing, Angermünde, Anklam, Arkona, Arnsberg-Neheim, Arnstein-Müdesheim, Artern, Attenkam, Aue, Augsburg, Bad Bergzabern, Bad Berleburg-Stünzel, Bad Dürkheim, Bad Hersfeld, Bad Kissingen, Bad Kreuznach, Bad Königshofen, Bad Lippspringe, Bad Marienberg, Bad Muskau, Bad Nauheim, Bad Neuenahr-Ahrweiler, Bad Salzuflen, Bad Salzungen-Gräfen


22 archives were successfully processed.


  110 html files deleted.
  154 metadata files deleted.
  22 zip files archived.

TU_temp_air_recent

searching descriptive PDFs... ['https://opendata.dwd.de/climate_environment/CDC/observations_germany/climate/hourly/air_temperature/BESCHREIBUNG_obsgermany_climate_hourly_air_temperature_de.pdf', 'https://opendata.dwd.de/climate_environment/CDC/observations_germany/climate/hourly/air_temperature/DESCRIPTION_obsgermany_climate_hourly_air_temperature_en.pdf']

Identifying available data from TU_Stundenwerte_Beschreibung_Stationen.txt

390 German weather stations with current hourly sun data remaining.
  Recording started between 18930101 and 20051201
  Cities: Alfhausen, Alsfeld-Eifa, Altenstadt, Altheim Kreis Biberach, Altomünster-Maisbrunn, Alzey, Amberg-Unterammersricht, Amerang-Pfaffing, Angermünde, Anklam, Arkona, Arnsberg-Neheim, Arnstein-Müdesheim, Artern, Attenkam, Aue, Augsburg, Bad Bergzabern, Bad Berleburg-Stünzel, Bad Dürkheim, Bad Hersfeld, Bad Kissingen, Bad Kreuznach, Bad 


23 archives were successfully processed.


searching descriptive PDFs... ['https://opendata.dwd.de/climate_environment/CDC/observations_germany/climate/hourly/air_temperature/BESCHREIBUNG_obsgermany_climate_hourly_air_temperature_de.pdf', 'https://opendata.dwd.de/climate_environment/CDC/observations_germany/climate/hourly/air_temperature/DESCRIPTION_obsgermany_climate_hourly_air_temperature_en.pdf']

Identifying available data from TU_Stundenwerte_Beschreibung_Stationen.txt

390 German weather stations with current hourly sun data remaining.
  Recording started between 18930101 and 20051201
  Cities: Alfhausen, Alsfeld-Eifa, Altenstadt, Altheim Kreis Biberach, Altomünster-Maisbrunn, Alzey, Amberg-Unterammersricht, Amerang-Pfaffing, Angermünde, Anklam, Arkona, Arnsberg-Neheim, Arnstein-Müdesheim, Artern, Attenkam, Aue, Augsburg, Bad Bergzabern, Bad Berleburg-Stünzel, Bad Dürkheim, Bad Hersfeld, Bad Kissingen, Bad Kreuznach, Bad Königshofen, Bad Lippspringe, Bad Marienberg, Bad Muskau, Bad Nauheim, Bad Neuenahr-Ahrweiler, Bad Sal


23 archives were successfully processed.


  115 html files deleted.
  161 metadata files deleted.
  23 zip files archived.

EB_temp_soil_recent

searching descriptive PDFs... ['https://opendata.dwd.de/climate_environment/CDC/observations_germany/climate/hourly/soil_temperature/BESCHREIBUNG_obsgermany_climate_hourly_soil_temperature_de.pdf', 'https://opendata.dwd.de/climate_environment/CDC/observations_germany/climate/hourly/soil_temperature/DESCRIPTION_obsgermany_climate_hourly_soil_temperature_en.pdf']

Identifying available data from EB_Stundenwerte_Beschreibung_Stationen.txt

268 German weather stations with current hourly sun data remaining.
  Recording started between 19490101 and 20051101
  Cities: Alfhausen, Alsfeld-Eifa, Altenstadt, Altheim Kreis Biberach, Alzey, Amerang-Pfaffing, Angermünde, Anklam, Arkona, Arnsberg-Neheim, Artern, Aue, Augsburg, Bad Bergzabern, Bad Dürkheim, Bad Hersfeld, Bad Kissingen, Bad Kreuznach, Bad Lauchstädt, Bad Lippspringe, Bad Marienberg, Bad Muskau, Bad Neuenahr-Ahrweiler, Bad Salzuflen, 


23 archives were successfully processed.


searching descriptive PDFs... ['https://opendata.dwd.de/climate_environment/CDC/observations_germany/climate/hourly/soil_temperature/BESCHREIBUNG_obsgermany_climate_hourly_soil_temperature_de.pdf', 'https://opendata.dwd.de/climate_environment/CDC/observations_germany/climate/hourly/soil_temperature/DESCRIPTION_obsgermany_climate_hourly_soil_temperature_en.pdf']

Identifying available data from EB_Stundenwerte_Beschreibung_Stationen.txt

268 German weather stations with current hourly sun data remaining.
  Recording started between 19490101 and 20051101
  Cities: Alfhausen, Alsfeld-Eifa, Altenstadt, Altheim Kreis Biberach, Alzey, Amerang-Pfaffing, Angermünde, Anklam, Arkona, Arnsberg-Neheim, Artern, Aue, Augsburg, Bad Bergzabern, Bad Dürkheim, Bad Hersfeld, Bad Kissingen, Bad Kreuznach, Bad Lauchstädt, Bad Lippspringe, Bad Marienberg, Bad Muskau, Bad Neuenahr-Ahrweiler, Bad Salzuflen, Bamberg, Barth, Baruth, Berge, Berlin Brandenburg, Berlin-Dahlem (FU), Berlin-Marzahn, Berlin-Tempelhof


23 archives were successfully processed.


  92 html files deleted.
  138 metadata files deleted.
  23 zip files archived.

P0_pressure_recent

searching descriptive PDFs... ['https://opendata.dwd.de/climate_environment/CDC/observations_germany/climate/hourly/pressure/BESCHREIBUNG_obsgermany_climate_hourly_pressure_de.pdf', 'https://opendata.dwd.de/climate_environment/CDC/observations_germany/climate/hourly/pressure/DESCRIPTION_obsgermany_climate_hourly_pressure_en.pdf']

Identifying available data from P0_Stundenwerte_Beschreibung_Stationen.txt

182 German weather stations with current hourly sun data remaining.
  Recording started between 19490101 and 20050908
  Cities: Altenstadt, Angermünde, Arkona, Artern, Augsburg, Bad Hersfeld, Bad Kissingen, Bad Lippspringe, Bad Marienberg, Bad Salzuflen, Bamberg, Barth, Baruth, Bergen, Berlin Brandenburg, Berlin-Dahlem (FU), Berlin-Tempelhof, Berus, Boizenburg, Boltenhagen, Braunlage, Braunschweig, Bremen, Bremerhaven, Bremervörde, Bremgarten (Fessenheim), Brocken, Büchel (Flugplatz), 


22 archives were successfully processed.


searching descriptive PDFs... ['https://opendata.dwd.de/climate_environment/CDC/observations_germany/climate/hourly/pressure/BESCHREIBUNG_obsgermany_climate_hourly_pressure_de.pdf', 'https://opendata.dwd.de/climate_environment/CDC/observations_germany/climate/hourly/pressure/DESCRIPTION_obsgermany_climate_hourly_pressure_en.pdf']

Identifying available data from P0_Stundenwerte_Beschreibung_Stationen.txt

182 German weather stations with current hourly sun data remaining.
  Recording started between 19490101 and 20050908
  Cities: Altenstadt, Angermünde, Arkona, Artern, Augsburg, Bad Hersfeld, Bad Kissingen, Bad Lippspringe, Bad Marienberg, Bad Salzuflen, Bamberg, Barth, Baruth, Bergen, Berlin Brandenburg, Berlin-Dahlem (FU), Berlin-Tempelhof, Berus, Boizenburg, Boltenhagen, Braunlage, Braunschweig, Bremen, Bremerhaven, Bremervörde, Bremgarten (Fessenheim), Brocken, Büchel (Flugplatz), Bückeburg, Carlsfeld, Celle, Chemnitz, Chieming, Cottbus, Cuxhaven, Deuselbach, Diepholz, Doberlug-Ki


22 archives were successfully processed.


In [15]:
# see all available data files
!wc -l ../*/w*/*/*prod* 
# !wc -l ../*/w*/*/*prod* > ../data/weather/file_list.txt


zsh:1: no matches found: ../*/w*/*/*prod*


In [16]:
# write all downloaded data files and their length into to file
log_file = '../data/weather/weather_data_file_summary.txt'
log = open(log_file, 'w')  
subprocess.call(["wc -l ../*/w*/*/*/*prod*"], stdout=log, stderr=log, shell=True)
log.close()

In [17]:
# iterate through log file
new_data = []
for item in open(log_file):
    if not item.strip().endswith("total") and not len(item.strip())==0:
        new_data.append(item.split("\\")[-1].split("_")[-1].split(".")[0])

# print station IDs having missing data files
max_file_count = 0
for item in sorted(set(new_data)):
    max_file_count = max(" ".join(new_data).count(item), max_file_count)

print("%d data files in total per weather station\n" % max_file_count)

print("Files with incomplete set of data files:")
complete_file_count = 0
for item in sorted(set(new_data)):
    count = " ".join(new_data).count(item)
    if count < max_file_count:
        print("  ", item, count, "files")
    else:
        complete_file_count += 1
print("\n%d locations with complete data sets" % complete_file_count)


29 data files in total per weather station

Files with incomplete set of data files:
   00053 1 files
   05100 28 files
   05404 9 files

21 locations with complete data sets


## Summary of hourly weather data

### Description of the dataset

- 36 files per weather station
- 2 files for most weather parameters: historical data + recent data  
  &rarr; only recent data must be updated to include the most recent weather information!
>
- core dataset based on solar data has 23 weather stations with data since 2005 up to today
- 21 weather stations have all data files
- missing information for:  
    - 05100 Trier-Petrisberg
    - 05404 Weihenstephan-Dürnast
    - 00053 [only in precipitation data, likely due to id-match with date information]


### Weather parameters

- potentially relevant weather parameters: 

Topic | Acronym | Comment
--- | --- | ---
solar | ST | solar incoming (total/diffuse) and longwave downward radiation
sun | SD | sunshine duration
||
cloudiness | N | cloud cover
cloud_type | CS | cloud cover, cloud type and cloud height in up to 4 layers
visibility | VV | visibility range
||
wind | FF | wind speed and wind direction
wind_synop | F | wind speed and wind direction
extreme_wind | FX | windspeed
||
weather_phenomena | WW | storms, hail, ... [numerically encoded](https://opendata.dwd.de/climate_environment/CDC/observations_germany/climate/hourly/weather_phenomena/recent/Wetter_Beschreibung.txt)


### Weather stations with complete dataset

- dates acc. to solar data (ST)

Stations_id | von_datum | bis_datum | Stationshoehe | geoBreite | geoLaenge | Stationsname | Bundesland
--- | --- | --- | --- | --- | --- | --- | --- 
00183 | 19810101 | 20230630 | 42 | 54.6791 | 13.4344 | Arkona | Mecklenburg-Vorpommern
00662 | 19580101 | 20230630 | 81 | 52.2915 | 10.4464 | Braunschweig | Niedersachsen
00853 | 19810101 | 20230630 | 416 | 50.7913 | 12.8720 | Chemnitz | Sachsen
01048 | 19960901 | 20230630 | 228 | 51.1278 | 13.7543 | Dresden-Klotzsche | Sachsen
01358 | 19580101 | 20230630 | 1213 | 50.4283 | 12.9536 | Fichtelberg | Sachsen
01684 | 20010101 | 20230630 | 239 | 51.1621 | 14.9506 | Görlitz | Sachsen
01975 | 20050101 | 20230630 | 11 | 53.6332 | 9.9881 | Hamburg-Fuhlsbüttel | Hamburg
02290 | 19530101 | 20230630 | 977 | 47.8009 | 11.0108 | Hohenpeißenberg | Bayern
02712 | 19770101 | 20230630 | 428 | 47.6952 | 9.1307 | Konstanz | Baden-Württemberg
03015 | 19810101 | 20230630 | 98 | 52.2085 | 14.1180 | Lindenberg | Brandenburg
03631 | 19640101 | 20230630 | 12 | 53.7123 | 7.1519 | Norderney | Niedersachsen
03987 | 19451231 | 20230630 | 81 | 52.3812 | 13.0622 | Potsdam | Brandenburg
04271 | 19980101 | 20230630 | 5 | 54.1803 | 12.0808 | Rostock-Warnemünde | Mecklenburg-Vorpommern
04336 | 19810101 | 20230630 | 319 | 49.2128 | 7.1077 | Saarbrücken-Ensheim | Saarland
04466 | 19800101 | 20230630 | 43 | 54.5275 | 9.5487 | Schleswig | Schleswig-Holstein
04642 | 19910101 | 20230630 | 21 | 52.8911 | 11.7297 | Seehausen | Sachsen-Anhalt
04928 | 19790101 | 20230630 | 314 | 48.8281 | 9.2000 | Stuttgart (Schnarrenberg) | Baden-Württemberg
05705 | 19570101 | 20230630 | 268 | 49.7704 | 9.9576 | Würzburg | Bayern
05779 | 19810101 | 20230630 | 877 | 50.7313 | 13.7516 | Zinnwald-Georgenfeld | Sachsen
05856 | 19970102 | 20230630 | 476 | 48.5451 | 13.3532 | Fürstenzell | Bayern
05906 | 19790101 | 20230630 | 98 | 49.5063 | 8.5584 | Mannheim | Baden-Württemberg


## Collect daily weather data

- data available [here](https://opendata.dwd.de/climate_environment/CDC/observations_germany/climate/daily/)
    - [climate](https://opendata.dwd.de/climate_environment/CDC/observations_germany/climate/daily/kl/historical/DESCRIPTION_obsgermany_climate_daily_kl_historical_en.pdf) general with multiple variables: **form of precipitation**, air temperature at 2 m, **precipitation parameters**, **precipitation height**, **wind velocity**, **cloud coverage**, **snow depth**, **sunshine duration**, air temperature near ground, **kind of precipitation**, **wind gust**, air pressure at station level, vapor pressure, relative humidity

### Check data availability


In [18]:
# general variables
out_path = "../data/weather/weather-daily/"
prepare_outdir(out_path)

# get first url for climate data
url = list_urls_daily[0]
web_tag = list_data_tags_daily[0]
data_tag = list_web_tags_daily[0]

# create output folders
prepare_outdir(out_path)

# save descriptive PDF as well
description_pdfs = get_file_list_from_html(url, "pdf")
for link in description_pdfs:
    filenames = (data_tag + "_" + link.split("/")[-1]).replace("__", "_")
    webpage = requests.get(link, allow_redirects=True)
    print(path+"/"+out_path)
    open(path+"/"+out_path+filenames, 'wb').write(webpage.content)

# get descriptive text file and screen it
txt_urls = get_file_list_from_html(url, descriptive_suffix)
if len(txt_urls) > 1:
    print("Multiple txt files on", url, "\n  ->", 
          [x.split("/")[-1] for x in txt_urls])

# download description file
file_list = []
for description_url in txt_urls: 
    filename = description_url.split("/")[-1]
    webpage = requests.get(description_url, allow_redirects=True)
    open(path+"/"+out_path+filename, 'wb').write(webpage.content)
    # required in case contain multiple text files
    if "beschreibung_stationen" in filename.lower():
        file_list.append(filename)

# identify available, informative weather stations from description file
list_ids = []
for filename in file_list:
    list_ids.extend(get_weather_station_IDs(out_path, filename, web_tag, data_tag))
base_ids = list_ids[:]

Created directory ./../data/weather/weather-daily


/Users/kathse/Documents/NeueFische/4_Capstone/capstone_solar_energy/notebooks/../data/weather/weather-daily/
/Users/kathse/Documents/NeueFische/4_Capstone/capstone_solar_energy/notebooks/../data/weather/weather-daily/
Multiple txt files on https://opendata.dwd.de/climate_environment/CDC/observations_germany/climate/daily/kl/recent/ 
  -> ['KL_Tageswerte_Beschreibung_Stationen.txt', 'KL_Tageswerte_mn4_Beschreibung_Stationen.txt']

Identifying available data from KL_Tageswerte_Beschreibung_Stationen.txt

481 German weather stations with current hourly sun data remaining.
  Recording started between 17810101 and 20051101
  Cities: Aldersbach-Kriestorf, Alfhausen, Alsfeld, Alsfeld-Eifa, Altenstadt, Altheim Kreis Biberach, Altmühlsee, Altomünster-Maisbrunn, Alzey, Amberg-Unterammersricht, Amerang-Pfaffing, Andernach, Angermünde, Anklam, Arkona, Arnsberg-Neheim, Arnstein-Müdesheim, Artern, Attenkam, Aue, Augsburg, Bad Arolsen-Volkhardinghausen, Bad Bergzabern, Bad Berka (Flugplatz), Bad Berl

### Download relevant data

- focus on the major cities of interest: Goerlitz (01684) and Konstanz (02712)

In [19]:
base_ids = ("01684", "02712")
for idx in range(len(list_web_tags_daily)):
    url = list_urls_daily[idx]
    web_tag = list_web_tags_daily[idx]
    data_tag = list_data_tags_daily[idx]

    # download files
    main(url, web_tag, data_tag, base_ids)

KL_climate_recent_daily

Multiple txt files on https://opendata.dwd.de/climate_environment/CDC/observations_germany/climate/daily/kl/recent/ 
  -> ['KL_Tageswerte_Beschreibung_Stationen.txt', 'KL_Tageswerte_mn4_Beschreibung_Stationen.txt']

Identifying available data from KL_Tageswerte_Beschreibung_Stationen.txt

481 German weather stations with current hourly sun data remaining.
  Recording started between 17810101 and 20051101
  Cities: Aldersbach-Kriestorf, Alfhausen, Alsfeld, Alsfeld-Eifa, Altenstadt, Altheim Kreis Biberach, Altmühlsee, Altomünster-Maisbrunn, Alzey, Amberg-Unterammersricht, Amerang-Pfaffing, Andernach, Angermünde, Anklam, Arkona, Arnsberg-Neheim, Arnstein-Müdesheim, Artern, Attenkam, Aue, Augsburg, Bad Arolsen-Volkhardinghausen, Bad Bergzabern, Bad Berka (Flugplatz), Bad Berleburg-Stünzel, Bad Dürkheim, Bad Harzburg, Bad Hersfeld, Bad Kissingen, Bad Kohlgrub (Rosshof), Bad Kreuznach, Bad Königshofen, Bad Lauchstädt, Bad Lippspringe, Bad Lobenstein, Bad Marienberg, 


2 archives were successfully processed.


Multiple txt files on https://opendata.dwd.de/climate_environment/CDC/observations_germany/climate/daily/kl/historical/ 
  -> ['KL_Tageswerte_Beschreibung_Stationen.txt', 'KL_Tageswerte_mn4_Beschreibung_Stationen.txt']

Identifying available data from KL_Tageswerte_Beschreibung_Stationen.txt

481 German weather stations with current hourly sun data remaining.
  Recording started between 17810101 and 20051101
  Cities: Aldersbach-Kriestorf, Alfhausen, Alsfeld, Alsfeld-Eifa, Altenstadt, Altheim Kreis Biberach, Altmühlsee, Altomünster-Maisbrunn, Alzey, Amberg-Unterammersricht, Amerang-Pfaffing, Andernach, Angermünde, Anklam, Arkona, Arnsberg-Neheim, Arnstein-Müdesheim, Artern, Attenkam, Aue, Augsburg, Bad Arolsen-Volkhardinghausen, Bad Bergzabern, Bad Berka (Flugplatz), Bad Berleburg-Stünzel, Bad Dürkheim, Bad Harzburg, Bad Hersfeld, Bad Kissingen, Bad Kohlgrub (Rosshof), Bad Kreuznach, Bad Königshofen, Bad Lauchstädt, Bad Lippspringe, Bad Lobenstein, Bad Marienberg, Bad Muskau, Bad Nauhe


2 archives were successfully processed.


searching descriptive PDFs... []

Identifying available data from wetter_tageswerte_Beschreibung_Stationen.txt

1 German weather stations with current hourly sun data remaining.
  Recording started between 19500101 and 19500101
  Cities: Berlin-Dahlem (FU)
  IDs 00403

Focussing on 2 cities with complete data.

Starting download of 2 files from url https://opendata.dwd.de/climate_environment/CDC/observations_germany/climate/daily/weather_phenomena/recent/
Created directory ./../data/weather/weather-daily/phenomena_recent_daily
Note: No file available for id 01684
Note: No file available for id 02712
phenomena_historical_daily

searching descriptive PDFs... []

Identifying available data from wetter_tageswerte_Beschreibung_Stationen.txt

1 German weather stations with current hourly sun data remaining.
  Recording started between 19500101 and 19500101
  Cities: Berlin-Dahlem (FU)
  IDs 00403

Focussing on 2 cities with complete data.

Starting download of 2 files from url https://openda


2 archives were successfully processed.


searching descriptive PDFs... []

Identifying available data from rr_wetter_tageswerte_Beschreibung_Stationen.txt
02977,19790101,20041231,375,51.5393,8.9112,Lichtenau in Westfalen,-Blankenrode,Nordrhein-Westfalen
03718,19830701,19851231,740,47.8977,7.9480,Oberried-Sankt Wilhelm (Forsthaus,),Baden-Württemberg

1 German weather stations with current hourly sun data remaining.
  Recording started between 19600101 and 19600101
  Cities: Berlin-Dahlem (FU)
  IDs 00403

Focussing on 2 cities with complete data.

Starting download of 2 files from url https://opendata.dwd.de/climate_environment/CDC/observations_germany/climate/daily/more_weather_phenomena/recent/
Created directory ./../data/weather/weather-daily/RR_morephenomena_recent_daily
Note: No file available for id 01684
Note: No file available for id 02712
RR_morephenomena_historical_daily

searching descriptive PDFs... []

Identifying available data from rr_wetter_tageswerte_Beschreibung_Stationen.txt
02977,19790101,20041231,375,51.53


2 archives were successfully processed.


In [20]:
# see all available data files
os.chdir(out_path)
!wc -l ./*/*prod* 

   57803 ./KL_climate_historical_daily/produkt_klima_tag_18600101_20221231_01684.txt
   23196 ./KL_climate_historical_daily/produkt_klima_tag_19590701_20221231_02712.txt
     551 ./KL_climate_recent_daily/produkt_klima_tag_20220123_20230726_01684.txt
     551 ./KL_climate_recent_daily/produkt_klima_tag_20220123_20230726_02712.txt
   40724 ./RR_morephenomena_historical_daily/produkt_rr_wetter_tag_18670729_20181231_01684.txt
   15827 ./RR_morephenomena_historical_daily/produkt_rr_wetter_tag_19721101_20171231_02712.txt
   48244 ./phenomena_historical_daily/produkt_wetter_tag_18670730_20181231_01684.txt
   16414 ./phenomena_historical_daily/produkt_wetter_tag_19721101_20171231_02712.txt
  203310 total


# Summary of daily weather data

## Description of the dataset

- only Goerlitz (01684) and Konstanz (02712) included here
>
- 4 files per weather station 
  - 2 files for climate file: historical data + recent data  
    &rarr; only recent data must be updated to include the most recent weather information!
  - weather phenomena only available for historical data  
    (little recent data available as these phenomena are not very common)
>
- measured climate parameters: 
  - **form of precipitation**
  - air temperature at 2 m
  - **precipitation parameters**
  - **precipitation height**
  - **wind velocity**
  - **cloud coverage**
  - **snow depth**
  - **sunshine duration**
  - air temperature near ground
  - **kind of precipitation**
  - **wind gust**
  - air pressure at station level
  - vapor pressure
  - relative humidity
